Repository community-scripts/ProxmoxVE, pull requests merged in 2024-12, with the labels that each got.

#618 qbittorrent: do not override the configuration port in systemd
  install/qbittorrent-install.sh
Labels: update script

#614 Stirling-PDF: replace dependency for v0.35.0 and add check and fix in stirling-pdf.sh
  ct/stirling-pdf.sh
  install/stirling-pdf-install.sh
Labels: update script

#538 SnipeIT install Script
  ct/snipeit.sh
  install/snipeit-install.sh
  json/snipeit.json
Labels: website, new script

#547 New script: Unbound LXC
  ct/unbound.sh
  install/unbound-install.sh
  json/unbound.json
Labels: website, new script

#567 New Script: Hoarder LXC
  ct/hoarder.sh
  install/hoarder-install.sh
  json/hoarder.json
Labels: website, new script

#595 New Script: Glance
  ct/glance.sh
  install/glance-install.sh
  json/glance.json
Labels: website, new script

#645 fix: vaultwarden info mismatch
  frontend/src/app/scripts/_components/ScriptAccordion.tsx
  json/vaultwarden.json
Labels: website

#648 chore: Update unbound logo to have only the actual logo
  json/unbound.json
Labels: website

#641 Script Update: SnipeIT
  ct/snipeit.sh
  install/snipeit-install.sh
  json/snipeit.json
Labels: website, update script

#612 New Script: Onedev
  ct/onedev.sh
  install/onedev-install.sh
  json/onedev.json
Labels: website, new script

#668 Update homepage.json documentation and website links
  json/homepage.json
Labels: website

#676 Update nginxproxymanager-install.sh
  install/nginxproxymanager-install.sh
Labels: update script

#688 Fix stdout in unifi.sh
  ct/unifi.sh
Labels: update script

#692 Fix `rm` bug in Vikunja update
  ct/vikunja.sh
Labels: update script

#650 PostgreSQL: Change authentication method from peer to md5 for UNIX sockets
  install/postgresql-install.sh
Labels: update script

#700 Bookstack: Fix Update function composer
  ct/bookstack.sh
Labels: update script

#706 fix: note component in json-editor getting out of focus when typing and revert theme switch animation
  frontend/src/app/json-editor/_components/Note.tsx
  frontend/src/styles/globals.css
Labels: website

#717 Fix bugs in Komga update
  ct/komga.sh
Labels: update script

#703 Update frontend CI/CD workflow
  .github/workflows/deploy-pages.yml
  .github/workflows/frontend-cicd.yml
  json/onedev.json
Labels: website, maintenance

#723 Fix Hoarder build failure by installing Chromium stable
  install/hoarder-install.sh
Labels: update script

#702 Zigbee2MQTT: Remove dev branch choice until v2.0.0 release
  install/zigbee2mqtt-install.sh
Labels: update script

#731 Bugfix: Include script name in website search
  frontend/src/components/CommandMenu.tsx
Labels: website

#736 Fix broken build.func
  misc/build.func
Labels: high risk

#691 Use MongoDB 4.4 in Unifi for non-AVX users
  install/unifi-install.sh
  json/unifi.json
Labels: website, update script

#740 Move homarr to Dashboards section
  json/homarr.json
Labels: website

#750 Fix PostgreSQL password bug in Umami install
  install/umami-install.sh
Labels: update script

#783 Add post-install note to mqtt.json
  json/mqtt.json
Labels: website

#781 Fix Z-Wave JS UI Breaking Change in CHANGELOG.md
  CHANGELOG.md
Labels: maintenance

#790 Fix port and website in nextcloudpi.json
  json/nextcloudpi.json
Labels: website

#793 Filter pull requests on main branch in changelog-pr.yml
  .github/workflows/changelog-pr.yml
Labels: maintenance

#792 Update jellyfin.sh / Fix infinite loop
  ct/jellyfin.sh
Labels: update script

#775 Fix config bug in Alpine Vaultwarden
  install/alpine-vaultwarden-install.sh
  json/vaultwarden.json
Labels: website, update script

#804 Update Notes & Documentation for Proxmox Backup Server
  json/pbs.json
Labels: website

#762 Fix Keycloak Update Function
  ct/keycloak.sh
Labels: update script

#815 Change MISC from red to green
  frontend/src/components/CommandMenu.tsx
Labels: website

#643 Massive Update: build.func | install.func | create_lxc.sh (Part 1)
  ct/alpine.sh
  ct/create_lxc.sh
  misc/alpine-install.func
  misc/build.func
  misc/install.func
Labels: high risk, update script, breaking change

#837 Increase Size | Description & Download-URL of Debian VM
  json/debian-vm.json
  vm/debian-vm.sh
Labels: website, update script

#536 New Script: LXC IP-Tag
  json/add-lxc-iptag.json
  misc/add-lxc-iptag.sh
Labels: website, new script

#847 Update Script: Remove Docker Compose Question
  install/docker-install.sh
Labels: update script

#851 Keeps the same style after writing the SEARCH icon
  misc/build.func
Labels: high risk

#855 Fix variable name for CT_TYPE override
  misc/build.func
Labels: high risk

#867 Fix ports ressources
  ct/adguard.sh
  ct/plex.sh
  json/photoprism.json
Labels: website, update script

#876 fix spinner on lxc-ip-tag
  misc/add-lxc-iptag.sh
Labels: update script

#879 calculate terminal size for header_info
  misc/build.func
Labels: high risk

#862 Small Changes to the PR Template
  .github/pull_request_template.md
Labels: maintenance

#865 Fix Alpine-Nextcloud: Bump PHP Version to 8.3
  install/alpine-nextcloud-install.sh
Labels: update script

#891 Moved Webmin to "Server & Networking"
  json/webmin.json
Labels: website

#890 New Metadata Category: "Coding & AI"
  json/code-server.json
  json/flowiseai.json
  json/forgejo.json
  json/gitea.json
  json/metadata.json
  json/openwebui.json
Labels: website

#591 New script: Part-DB LXC
  ct/part-db.sh
  install/part-db-install.sh
  json/part-db.json
Labels: website, new script

#902 [Frigate] Remove SSE 4.2 from instruction set supporting OpenVino
  install/frigate-install.sh
Labels: update script

#909 Fix script path formatting in InstallMethod component
  frontend/src/app/json-editor/_components/InstallMethod.tsx
Labels: website

#898 Fix Part-DB Docu (cred command)
  json/part-db.json
Labels: website

#918 Fix Omada - Crawling latest version
  ct/omada.sh
  install/omada-install.sh
Labels: update script

#844 Fix: Bookstack Update Function
  ct/bookstack.sh
Labels: update script

#640 New Script: Zammad
  ct/zammad.sh
  install/zammad-install.sh
  json/zammad.json
Labels: website, new script

#657 New Script: Apache Guacamole
  ct/apache-guacamole.sh
  install/apache-guacamole-install.sh
  json/apache-guacamole.json
Labels: website, new script

#940 Add Login Note for Checkmk
  json/checkmk.json
Labels: website

#948 Fix: Remove PHP Key generation in Bookstack Update
  ct/bookstack.sh
Labels: update script

#954 Update checkmk description
  json/checkmk.json
Labels: website

#961 update Port in homeassistant-core CT
  ct/homeassistant-core.sh
Labels: update script

#989 Update emby.sh to correct port
  ct/emby.sh
Labels: update script

#991 Fix Navidrome Update & Install
  ct/navidrome.sh
  install/navidrome-install.sh
Labels: update script

#1007 Doubled RAM for SAB
  ct/sabnzbd.sh
Labels: update script

#933 Fix Script: Alpine Nextcloud Upload File Size Limit
  install/alpine-nextcloud-install.sh
Labels: update script

#947 add: pve-datacenter-manager
  ct/proxmox-datacenter-manager.sh
  install/proxmox-datacenter-manager-install.sh
  json/proxmox-datacenter-manager.json
Labels: website, new script

#1013 Fix Proxmox DataCenter: incorrect build.func url
  ct/proxmox-datacenter-manager.sh
Labels: update script

#943 New Script: 2FAuth
  ct/2fauth.sh
  install/2fauth-install.sh
  json/2fauth.json
Labels: website, new script

#992 ensure all RFC1918 local Ipv4 addresses are in iptag script
  misc/add-lxc-iptag.sh
Labels: update script

#1019 New Script: Jenkins
  ct/jenkins.sh
  install/jenkins-install.sh
  json/jenkins.json
Labels: website, new script

#1027 ChangeDetection Update: Update also Browsers
  ct/changedetection.sh
Labels: update script

#1035 Updated SAB documentation based on RAM increase
  json/sabnzbd.json
Labels: website

#291 new scripts for Authentik
  ct/authentik.sh
  install/authentik-install.sh
  json/authentik.json
Labels: website, new script

#1040 Add scripts for automated development contribution
  .github/CONTRIBUTING.md
  .github/CONTRIBUTOR_GUIDE/CONTRIBUTING.md
  .github/CONTRIBUTOR_GUIDE/ct/AppName.md
  .github/CONTRIBUTOR_GUIDE/ct/AppName.sh
  .github/CONTRIBUTOR_GUIDE/dev-scripts/README.md
  .github/CONTRIBUTOR_GUIDE/dev-scripts/change_lxc.sh
  .github/CONTRIBUTOR_GUIDE/dev-scripts/cleanup_lxc.sh
  .github/CONTRIBUTOR_GUIDE/dev-scripts/new_lxc.sh
  .github/CONTRIBUTOR_GUIDE/install/AppName-install.md
  .github/CONTRIBUTOR_GUIDE/install/AppName-install.sh
  .github/CONTRIBUTOR_GUIDE/json/AppName.json
  .github/CONTRIBUTOR_GUIDE/json/AppName.md
Labels: maintenance

#1042 fix Tags for Advanced Settings
  misc/build.func
Labels: high risk

#1044 Patch Figlet Repo if missing
  misc/build.func
Labels: high risk

#1039 Apache-Guacamole script bug fix
  install/apache-guacamole-install.sh
Labels: update script

#1046 Add 8.0 for MongoDB Installation
  ct/mongodb.sh
  install/mongodb-install.sh
Labels: update script

#1048 Update Zabbix to 7.2. Release
  ct/zabbix.sh
  install/zabbix-install.sh
Labels: update script

#1065 Authentik: added missing port to access url
  ct/authentik.sh
Labels: update script

#1067 Add an IP-Update for MOTD if IP Changed
  misc/build.func
Labels: maintenance, update script, breaking change

#1069 Zabbix: Fix SQL Path for 7.2
  install/zabbix-install.sh
Labels: update script

#1072 Add Figlet into Repo | Creation of local ASCII Header
  misc/build.func
Labels: maintenance, update script, breaking change

#1076 Add new script: Grist
  ct/grist.sh
  install/grist-install.sh
  json/grist.json
Labels: website, new script

#1064 New Script: TeddyCloud Server
  ct/teddycloud.sh
  install/teddycloud-install.sh
  json/teddycloud.json
Labels: website, new script

#1073 Introduce editorconfig for more consistent formatting
  .editorconfig
Labels: guide, maintenance

#1094 fix: Update add-lxc-iptag.json warn to warning
  json/add-lxc-iptag.json
Labels: website

#1091 Fix Install / Update on Grist Script
  ct/grist.sh
  install/grist-install.sh
Labels: update script

#1103 Fix Trilium Website to TriliumNext
  json/trilium.json
Labels: website

#1107 fix: add homepage version during build step
  ct/homepage.sh
  install/homepage-install.sh
Labels: update script

#1105 [Archivebox] Fix wrong port being printed post install.
  ct/archivebox.sh
Labels: update script

#1124 Netbox: Updating URL to https
  ct/netbox.sh
Labels: update script

#1129 Fix Homepage-Script: Installation/Update
  ct/homepage.sh
  install/homepage-install.sh
Labels: update script

#1122 fix: guacd service not start during Apache-Guacamole script installation process
  install/apache-guacamole-install.sh
Labels: update script

#1133 Fix: Figlet Version & Font Check
  misc/build.func
Labels: high risk, update script, breaking change

#1131 Add ExecReload to prometheus.service
  install/prometheus-install.sh
Labels: update script, breaking change

#1137 Fix: Copy issue after update in Bookstack LXC
  ct/bookstack.sh
Labels: update script
