Repository community-scripts/ProxmoxVE, pull requests merged in 2024-11, with the labels that each got.

#114 Docs: Fix typo in neo4j.json
  json/neo4j.json
Labels: documentation

#137 Added "(Patience)" to the Updating Ghostscript message
  ct/paperless-ngx.sh
Labels: documentation

#209 Suggested wording and improvements to README
  README.md
Labels: documentation, not a script issue, maintenance

#230 Add JSON Generator page for easier configuring of new metadata
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/json-editor/_components/Categories.tsx
  frontend/src/app/json-editor/_components/InstallMethod.tsx
  frontend/src/app/json-editor/_components/Note.tsx
  frontend/src/app/json-editor/_schemas/schemas.ts
  frontend/src/app/json-editor/page.tsx
  frontend/src/components/ui/alert.tsx
  frontend/src/components/ui/calendar.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/src/config/siteConfig.tsx
Labels: website

#252 Fix frontend bug
  frontend/src/app/page.tsx
Labels: website

#235 Update pihole-install.sh
  install/pihole-install.sh
  json/pihole.json
Labels: documentation, update script

#260 Correct website link for NZBGet
  json/nzbget.json
Labels: documentation, website, maintenance

#263 Update mysql.json
  json/mysql.json
Labels: documentation

#249 Add Option "check_storage" and "check_container_ressources"
  misc/build.func
Labels: high risk

#264 Update cloudflared-install.sh
  install/cloudflared-install.sh
  json/cloudflared.json
Labels: documentation, update script

#265 Optimize website json-editor page and components
  frontend/src/app/json-editor/_components/Categories.tsx
  frontend/src/app/json-editor/_components/InstallMethod.tsx
  frontend/src/app/json-editor/_components/Note.tsx
  frontend/src/app/json-editor/page.tsx
Labels: frontend

#266 Update cloudflared.json
  json/cloudflared.json
Labels: documentation

#271 Add Recyclarr LXC
  ct/recyclarr.sh
  install/recyclarr-install.sh
  json/recyclarr.json
Labels: documentation, new script

#259 Add Wavelog Script
  ct/wavelog.sh
  install/wavelog-install.sh
  json/wavelog.json
Labels: documentation, new script

#281 Enhance getInstallCommand to support Alpine variant in InstallCommand component
  frontend/src/app/scripts/_components/ScriptItems/InstallCommand.tsx
Labels: frontend

#282 Update Wavelog icon
  json/wavelog.json
Labels: documentation

#279 Fix AlertColors info style in site config for consistent dark mode appearance
  frontend/src/app/scripts/_components/ScriptItems/Alerts.tsx
  frontend/src/config/siteConfig.tsx
Labels: frontend

#285 Increase Ressources for vaultwarden and check storage
  CHANGELOG.md
  ct/vaultwarden.sh
  json/vaultwarden.json
Labels: documentation, maintenance, update script

#261 Update Wireguard LXC - Information about WGDashboard added
  ct/wireguard.sh
  install/wireguard-install.sh
  json/wireguard.json
Labels: documentation, website, update script

#292 Wavelog - Small Adjustment
  install/wavelog-install.sh
  json/wavelog.json
Labels: documentation, update script

#275 Add Komga LXC
  ct/komga.sh
  install/komga-install.sh
  json/komga.json
Labels: documentation, new script

#297 Use website label in autolabeler
  .github/autolabeler-config.json
  .github/workflows/autolabeler.yml
Labels: maintenance

#298 Fix Komga logo
  json/komga.json
Labels: documentation

#299 Add github workflow for automatic changelog PR
  .github/changelog-pr-config.json
  .github/workflows/changelog-pr.yml
  CHANGELOG.md
Labels: maintenance

#303 Add Note for Komga Installation (Website)
  json/komga.json
Labels: documentation, website, maintenance

#317 Fix optional installs in Cockpit LXC
  ct/cockpit.sh
Labels: bug, update script

#310 Verify changes before commit in changelog-pr.yml
  .github/workflows/changelog-pr.yml
Labels: maintenance

#306 Linkwarden - Harmonize Script, Add Monolith & Bugfixing
  ct/linkwarden.sh
  install/linkwarden-install.sh
  json/linkwarden.json
Labels: bug, website, update script

#331 Bugfix: Wallos Patch (Cron Log & Media Backup)
  ct/wallos.sh
  install/wallos-install.sh
Labels: update script

#329 Added additional instructions to nginxproxymanager
  json/nginxproxymanager.json
Labels: website

#349 Fix: add gnupg to installed dependencies
  install/linkwarden-install.sh
Labels: update script

#339 Fix Wallos Update
  ct/wallos.sh
Labels: update script

#352 [chore] Update FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, maintenance

#356 Linkwarden: Move Secret Key above in install.sh
  install/linkwarden-install.sh
Labels: update script

#226 [github]: add new Frontend_Report / Issue_Report & optimize config.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/frontend_report.yml
  .github/ISSUE_TEMPLATE/website-issue.yaml
Labels: documentation, enhancement, maintenance

#371 Refactor Buttons component to use a ButtonLink for cleaner code, simplifying the source URL generation and layout
  frontend/src/app/scripts/_components/ScriptItems/Buttons.tsx
  frontend/src/app/scripts/_components/ScriptItems/DefaultPassword.tsx
  frontend/src/app/scripts/_components/ScriptItems/DefaultSettings.tsx
Labels: website

#370 Add *Arr Suite category for Website
  json/autobrr.json
  json/bazarr.json
  json/homarr.json
  json/lidarr.json
  json/metadata.json
  json/notifiarr.json
  json/prowlarr.json
  json/radarr.json
  json/readarr.json
  json/recyclarr.json
  json/sonarr.json
  json/tdarr.json
  json/whisparr.json
Labels: enhancement, website

#376 LinkWarden: Moved PATH into service
  install/linkwarden-install.sh
Labels: update script

#378 Proxmox VE Cron LXC Updater: Add tteck's notes.
  json/cron-update-lxcs.json
Labels: website

#374 Replace dash "-" with "/" in metadata
  json/metadata.json
Labels: website

#405 Website: Add discord link to navbar
  frontend/src/config/siteConfig.tsx
Labels: website

#403 Fix incorrect hdd values in json files
  json/debian-vm.json
  json/haos-vm.json
  json/nextcloud-vm.json
  json/openwrt.json
  json/owncloud-vm.json
  json/pimox-haos-vm.json
  json/ubuntu2204-vm.json
  json/ubuntu2404-vm.json
Labels: website

#411 Add PostInstall Documentation to zigbee2mqtt.json
  json/zigbee2mqtt.json
Labels: website

#397 Add new LXC: Kimai
  ct/kimai.sh
  install/kimai-install.sh
  json/kimai.json
Labels: website, new script

#391 Add new LXC: NextPVR
  ct/nextpvr.sh
  install/nextpvr-install.sh
  json/nextpvr.json
Labels: website, new script

#402 Remove old resource message from vaultwarden
  ct/vaultwarden.sh
Labels: update script

#413 RDTClient Remove .NET 8.0 | Add .NET 9.0
  ct/rdtclient.sh
  install/rdtclient-install.sh
Labels: update script

#416 Use github app in changelog-pr.yml and add auto approval
  .github/workflows/changelog-pr.yml
Labels: maintenance

#383 Add .env file support for HomeBox
  install/homebox-install.sh
  json/homebox.json
Labels: website, update script

#431 Patch PostInstall-Script to PVE 8.3 | Add PVE 8.3 in Security
  SECURITY.md
  misc/post-pve-install.sh
Labels: maintenance, update script

#440 Fix Vikunja Update
  ct/vikunja.sh
Labels: update script

#441 Fixed Typo
  json/openwrt.json
Labels: website

#426 Frontend: fix reported issue with json-editor page and add OS select in installmethod
  frontend/src/app/json-editor/_components/InstallMethod.tsx
  frontend/src/config/siteConfig.tsx
  frontend/src/lib/types.ts
Labels: website

#455 Fix Actual Budget install missing build tools
  install/actualbudget-install.sh
Labels: update script

#461 Remove newline in changelog-pr action
  .github/workflows/changelog-pr.yml
  CHANGELOG.md
Labels: maintenance

#474 Fix newline issue in changelog pr
  .github/workflows/changelog-pr.yml
  CHANGELOG.md
Labels: maintenance

#442 New script: listmonk LXC
  ct/listmonk.sh
  install/listmonk-install.sh
  json/listmonk.json
Labels: website, new script

#481 Add release title to github-release.yml
  .github/workflows/github-release.yml
Labels: maintenance

#506 fixed zoraxy website url
  json/zoraxy.json
Labels: website

#515 Fix upload folder in listmonk LXC
  ct/listmonk.sh
  install/listmonk-install.sh
Labels: update script

#511 Remove Scrypted
  ct/scrypted.sh
  install/scrypted-install.sh
  json/scrypted.json
Labels: website, breaking change, delete script

#517 Fix bugs in Calibre-Web update
  ct/calibre-web.sh
Labels: update script

#524 Fix Vikunja install script to prevent database deletion upon updating
  install/vikunja-install.sh
Labels: update script

#527 Zabbix: Use Agent2 as Default | Update Script added | some other Improvements
  ct/zabbix.sh
  install/zabbix-install.sh
  json/zabbix.json
Labels: website, update script, breaking change

#319 Install MongoDB 4.2 for non-AVX CPUs in Unifi LXC
  ct/unifi.sh
  install/unifi-install.sh
  json/unifi.json
Labels: website, update script

#534 fix: install mosquitto from mosquitto repo
  install/mqtt-install.sh
Labels: update script

#528 Patch Netbird Script | Container Boot-Check | Debian/Ubuntu Only
  json/add-netbird-lxc.json
  misc/add-netbird-lxc.sh
Labels: website, update script

#543 Fix json error in zabbix.json
  json/zabbix.json
Labels: website

#545 Fix another json error in add-netbird-lxc.json
  json/add-netbird-lxc.json
Labels: website

#529 Remove changing DISK_REF for zfspool mikrotik-routeros.sh
  vm/mikrotik-routeros.sh
Labels: update script

#564 Fix MongoDB install in Unifi script
  install/unifi-install.sh
Labels: update script

#535 Add update script to Pocketbase
  ct/pocketbase.sh
  install/pocketbase-install.sh
  json/pocketbase.json
Labels: website, update script

#577 Fix Kimai Apache2 Rights
  install/kimai-install.sh
Labels: update script

#576 New Script: Inspircd
  ct/inspircd.sh
  install/inspircd-install.sh
  json/inspircd.json
Labels: website, new script

#574 New Script: LubeLogger
  ct/lubelogger.sh
  install/lubelogger-install.sh
  json/lubelogger.json
Labels: website, new script

#571 New Script: The Lounge IRC
  ct/thelounge.sh
  install/thelounge-install.sh
  json/thelounge.json
Labels: website, new script

#599 Convert line endings in the-lounge.sh
  ct/the-lounge.sh
  install/the-lounge-install.sh
Labels: update script

#605 add some Information for Monitor-All Script
  json/monitor-all.json
Labels: website
