Repository community-scripts/ProxmoxVE, pull requests merged in 2025-06, with the labels that each got.

#4887 AdventureLog: add login credentials info
  frontend/public/json/adventurelog.json
Labels: website, json

#4848 make Pulse installation non-interactive
  ct/pulse.sh
  frontend/public/json/pulse.json
  install/pulse-install.sh
Labels: update script, breaking change, refactor

#4906 PVE-Privilege-Converter
  frontend/public/json/pve-privilege-converter.json
  tools/pve/pve-privilege-converter.sh
Labels: new script

#4918 MySQL/MariaDB: fix create user with password
  install/2fauth-install.sh
  install/alpine-nextcloud-install.sh
  install/apache-guacamole-install.sh
  install/bookstack-install.sh
  install/dolibarr-install.sh
  install/firefly-install.sh
  install/ghost-install.sh
  install/glpi-install.sh
  install/kimai-install.sh
  install/monica-install.sh
  install/paymenter-install.sh
  install/pelican-panel-install.sh
  install/phpipam-install.sh
  install/plant-it-install.sh
  install/projectsend-install.sh
  install/pterodactyl-panel-install.sh
  install/shinobi-install.sh
  install/snipeit-install.sh
  install/wavelog-install.sh
Labels: update script, bugfix

#4924 [core] Varius fixes to Config file feature
  misc/build.func
  misc/config-file.func
Labels: maintenance, high risk, update script, core

#4927 [core] add hw-accelerated for immich, openwebui / remove scrypted
  misc/build.func
Labels: maintenance, high risk, core

#4937 Kasm: Swap fix
  ct/kasm.sh
  install/kasm-install.sh
Labels: website, update script, bugfix, json, refactor

#4952 netbox: correct website URL
  frontend/public/json/netbox.json
Labels: website, json

#4951 Pulse: add correct Port for URL output
  ct/pulse.sh
Labels: update script

#4954 [refactor] Seelf
  ct/seelf.sh
  install/seelf-install.sh
Labels: update script, bugfix, refactor

#4968 Tianji: Update dependencies
  ct/tianji.sh
  install/tianji-install.sh
Labels: invalid, update script, feature, bugfix

#4974 Homarr: add nodejs upgrade
  ct/homarr.sh
Labels: update script, bugfix

#4989 Zipline: Fix PostgreSQL install
  install/zipline-install.sh
Labels: update script, bugfix

#4990 Cron LXC Updater: correction of modified cronjob command
  frontend/public/json/cron-update-lxcs.json
Labels: invalid, website, json

#5000 Zitadel: Upgrade Install to PSQL 17
  install/zitadel-install.sh
Labels: update script, feature

#4998 Emby: Fix not showing as updateable on website
  frontend/public/json/emby.json
Labels: invalid, website, json

#5014 MeTube: Remove script from website temporarily
  frontend/public/json/metube.json.bak
Labels: invalid, website

#5038 declare pingvin-share as updateable
  frontend/public/json/pingvin.json
Labels: invalid, website, json

#5046 Immich: Align read command text output
  install/immich-install.sh
Labels: invalid, update script, bugfix

#5047 Alpine Rclone: Remove storage checks
  ct/alpine-rclone.sh
Labels: invalid, update script, refactor

#5056 zot: fix missing var (Dev -> Main)
  install/zot-registry-install.sh
Labels: update script, bugfix

#5070 Minarca: Update logo
  frontend/public/json/minarca.json
Labels: invalid, website, json

#5065 GoMFT: Remove from website temporarily
  frontend/public/json/gomft.json.bak
Labels: website

#5080 [core] Prevent API form sending Data when disabled
  misc/api.func
  misc/build.func
Labels: maintenance, api, core

#5085 Immich: Update JSON
  frontend/public/json/immich.json
Labels: website, json

#5090 Tinyauth: Fix creation of service file
  install/alpine-tinyauth-install.sh
Labels: update script, bugfix

#5109 install.func
  misc/install.func
Labels: invalid, maintenance, high risk, core

#5120 Zigbee2MQTT: Fix missing directory
  install/alpine-zigbee2mqtt-install.sh
Labels: update script, bugfix

#5127 Update dolibarr-install.sh - Get largest version number
  install/dolibarr-install.sh
Labels: update script, bugfix

#5130 flowiseai: set NodeJS to Version 20
  install/flowiseai-install.sh
Labels: update script, bugfix

#5159 Firefly: Add Data Importer to LXC
  ct/firefly.sh
  frontend/public/json/firefly.json
  install/firefly-install.sh
Labels: website, update script, json

#5152 Refactor: IP-Tag
  frontend/public/json/add-iptag.json
  frontend/public/json/add-lxc-iptag.json
  tools/pve/add-iptag.sh
  tools/pve/add-lxc-iptag.sh
Labels: website, refactor

#5162 Kasm: Storing Creds Fix
  install/kasm-install.sh
Labels: update script, bugfix

#5179 Update default image asset in the public directory and update api route to only search for files that end with .json
  frontend/public/defaultimg.png
  frontend/src/app/api/categories/route.ts
Labels: website, feature, bugfix

#5182 [core] Move install_php() from VED to main
  misc/tools.func
Labels: maintenance, update script, core

#5189 Update default image asset in the public directory
  frontend/public/defaultimg.png
Labels: website, feature

#5216 LibreTranslate: Add .env for easier configuration
  install/libretranslate-install.sh
Labels: update script, feature

#5213 IPTag: Better explanation
  frontend/public/json/add-iptag.json
Labels: website, json

#5226 Update IP-Tag
  tools/pve/add-iptag.sh
Labels: bugfix

#5227 Immich: ensure in proper working dir when updating
  ct/immich.sh
Labels: update script, bugfix

#5235 gitea-mirror: increase build ressources
  ct/gitea-mirror.sh
  frontend/public/json/gitea-mirror.json
Labels: website, update script, bugfix, json

#5241 tools.func: Standardized and Renamed Setup Functions
  misc/tools.func
Labels: maintenance, update script, core

#5231 Immich: fix prompt clobber issue
  install/immich-install.sh
Labels: update script, bugfix

#5248 FileBrowser Quantum
  frontend/public/json/filebrowser-quantum.json
  tools/addon/filebrowser-quantum.sh
Labels: website, new script

#5254 Refactor all VM's to same logic & functions
  vm/archlinux-vm.sh
  vm/docker-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/owncloud-vm.sh
  vm/pimox-haos-vm.sh
Labels: update script, refactor

#5025 Immich: prepare for v1.135.0
  ct/immich.sh
  frontend/public/json/immich.json
  install/immich-install.sh
Labels: website, update script, breaking change, bugfix, json

#5291 [core]: add validation and replace recursion for invalid inputs in adv. settings
  misc/build.func
Labels: maintenance, high risk, feature, core

#5284 Ubuntu 25.04 VM
  frontend/public/json/ubuntu2504-vm.json
  vm/ubuntu2504-vm.sh
Labels: website, new script

#5305 (turnkey) Add OpenLDAP as a TurnKey option
  turnkey/turnkey.sh
Labels: update script, feature

#5301 changedetection: add msedge as Browser dependency
  ct/changedetection.sh
Labels: update script, bugfix

#5313 PLANKA: Better DB password generate
  install/planka-install.sh
Labels: update script, bugfix

#5320 Refactor: migrate Jupyter Notebook to uv-based installation with update support
  ct/jupyternotebook.sh
  install/jupyternotebook-install.sh
Labels: update script, refactor

#5322 Argus: fix wrong port on website
  frontend/public/json/argus.json
Labels: website, json

#5316 [core]: unify misc/*.func scripts with centralized logic from core.func
  misc/alpine-install.func
  misc/api.func
  misc/build.func
  misc/config-file.func
  misc/core.func
  misc/create_lxc.sh
  misc/install.func
Labels: maintenance, update script, core

#5336 Huntarr: Fix duplicate update status messages
  ct/huntarr.sh
Labels: update script, bugfix

#5332 Immich: remove unneeded tmp_file
  ct/immich.sh
  install/immich-install.sh
Labels: update script, bugfix

#5361 gitea: Update gitea.sh to stop update failures
  ct/gitea.sh
Labels: update script, bugfix

#5355 Immich: unpin release; use fetch & deploy function for update
  ct/immich.sh
  install/immich-install.sh
Labels: update script, refactor

#5377 alpine: increase hdd to 1gb
  ct/alpine.sh
  frontend/public/json/alpine.json
Labels: website, update script, json

#5388 changedetection: fix: hermetic msedge
  ct/changedetection.sh
Labels: update script, bugfix

#5391 PLANKA: Fix the update procedure
  ct/planka.sh
Labels: update script, bugfix

#5397 [core]: tools.func -> autoupdate npm to newest version on install
  misc/tools.func
Labels: maintenance, update script, core

#5396 Alpine-Forgejo by @Johann3s-H
  ct/alpine-forgejo.sh
  frontend/public/json/forgejo.json
  install/alpine-forgejo-install.sh
Labels: new script

#5412 Refactor: Prometheus PVE Exporter to uv based install
  ct/prometheus-pve-exporter.sh
  install/prometheus-pve-exporter-install.sh
Labels: update script, refactor

#5411 Refactor: MeTube to uv based install
  ct/metube.sh
  frontend/public/json/metube.json
  frontend/public/json/metube.json.bak
  install/metube-install.sh
Labels: website, update script, refactor

#5418 Update all Alpine Scripts to atleast 1GB HDD
  ct/alpine-it-tools.sh
  ct/alpine-zigbee2mqtt.sh
  frontend/public/json/alpine-it-tools.json
  frontend/public/json/zigbee2mqtt.json
Labels: website, update script, bugfix, json

#5423 Minio: use latest version or latest feature rich version
  ct/minio.sh
  install/minio-install.sh
Labels: update script, feature

#5434 bump scripts (Installer) from Ubuntu 22.04 to Ubuntu 24.04 (agentdvr, emby, jellyfin, plex, shinobi)
  ct/agentdvr.sh
  ct/emby.sh
  ct/jellyfin.sh
  ct/plex.sh
  ct/shinobi.sh
  frontend/public/json/agentdvr.json
  frontend/public/json/emby.json
  frontend/public/json/jellyfin.json
  frontend/public/json/plex.json
  frontend/public/json/shinobi.json
  frontend/public/json/ubuntu.json
Labels: update script, breaking change

#5435 GoMFT: tmpl bugfix to work with current version until a new release pushed
  ct/gomft.sh
  frontend/public/json/gomft.json
  install/gomft-install.sh
Labels: update script, bugfix

#5450 YunoHost: add Update-Function
  ct/yunohost.sh
  frontend/public/json/yunohost.json
Labels: update script, feature

#5458 Docmost: Increase resources
  ct/docmost.sh
  frontend/public/json/docmost.json
Labels: invalid, website, update script, json

#5461 Update Tooltips component to conditionally display updateable status based on item type
  frontend/src/app/scripts/_components/ScriptItems/Tooltips.tsx
Labels: website, bugfix

#5464 Enhance InstallCommand component to support Gitea as an alternative source for installation scripts.
  frontend/src/app/scripts/_components/ScriptItems/InstallCommand.tsx
Labels: website, feature

#5453 Website: mark VM's and "OS"-LXC's as updatable
  frontend/public/json/alpine.json
  frontend/public/json/archlinux-vm.json
  frontend/public/json/debian-vm.json
  frontend/public/json/debian.json
  frontend/public/json/docker-vm.json
  frontend/public/json/haos-vm.json
  frontend/public/json/mikrotik-routeros.json
  frontend/public/json/nextcloud-vm.json
  frontend/public/json/openwrt.json
  frontend/public/json/opnsense-vm.json
  frontend/public/json/owncloud-vm.json
  frontend/public/json/pimox-haos-vm.json
  frontend/public/json/postgresql.json
  frontend/public/json/ubuntu.json
  frontend/public/json/ubuntu2204-vm.json
  frontend/public/json/ubuntu2404-vm.json
  frontend/public/json/ubuntu2410-vm.json
  frontend/public/json/ubuntu2504-vm.json
Labels: website, json

#5486 [tools] Fix setup_mongodb function
  misc/tools.func
Labels: maintenance, update script, core

#5517 wizarr: remove unneeded tmp file
  ct/wizarr.sh
Labels: update script, bugfix

#5523 push-to-gitea.yaml
  .github/workflows/push-to-gitea.yaml
Labels: invalid, maintenance, github

#5534 Ollama: Clean up old Ollama files before running update
  ct/ollama.sh
  ct/openwebui.sh
Labels: update script, bugfix

#5542 push-to-gitea.yaml
  .github/workflows/push-to-gitea.yaml
Labels: invalid, maintenance, github

#5552 fix bug in tooltip that would always render 'updateable'
  frontend/src/app/scripts/_components/ScriptItems/install-command.tsx
  frontend/src/app/scripts/_components/script-items/tool-tips.tsx
Labels: website, bugfix

#5548 Linkwarden: Add backing up of data folder to the update function
  ct/linkwarden.sh
Labels: update script, bugfix

#5549 Update script-item.tsx
  frontend/src/app/scripts/_components/script-item.tsx
Labels: website

#5204 Add cron-job api-key env variable to homarr script
  ct/homarr.sh
  install/homarr-install.sh
Labels: update script, feature

#5575 [core]: add ipv6 configuration support
  misc/build.func
Labels: maintenance, update script, feature, core

#5560 Immich: make changes to automatically enable QuickSync
  install/immich-install.sh
Labels: update script, bugfix

#5586 Alpine Syncthing
  ct/alpine-syncthing.sh
  frontend/public/json/syncthing.json
  install/alpine-syncthing-install.sh
Labels: new script
