Repository community-scripts/ProxmoxVE, pull requests merged in 2025-02, with the labels that each got.

#1913 New script: Baïkal
  ct/baikal.sh
  install/baikal-install.sh
  json/baikal.json
Labels: website, new script

#1917 Bug fix: Paymenter
  ct/paymenter.sh
  install/paymenter-install.sh
Labels: update script

#1922 [DCMA] Delete scripts 5etools and pf2etools - Copyright abuse
  ct/5etools.sh
  ct/headers/5etools
  ct/headers/pf2etools
  ct/pf2etools.sh
  install/5etools-install.sh
  install/pf2etools-install.sh
  json/5etools.json
  json/pf2etools.json
Labels: website, breaking change, delete script

#1938 fix z2m update function to 2.1.0
  ct/zigbee2mqtt.sh
Labels: update script

#1950 Prometheus PVE Exporter: Add `--default-timeout=300` to pip install commands
  ct/prometheus-pve-exporter.sh
  install/prometheus-pve-exporter-install.sh
Labels: update script

#1956 Fix typo in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: invalid

#1961 Prometheus Proxmox VE Exporter: Set correct website slug
  json/prometheus-pve-exporter.json
Labels: website

#1962 Fix: MSSQL-Server: Better gpg handling
  install/sqlserver2022-install.sh
Labels: update script

#1957 Fix Hoarder corepack install/update error
  ct/hoarder.sh
  install/hoarder-install.sh
Labels: update script

#1965 Fix: FS-Trim Cancel / Error-Button
  misc/fstrim.sh
Labels: update script

#1964 Fix: Grist ran into a heap space during the update
  ct/grist.sh
  json/grist.json
Labels: website, update script

#1967 [API] Update build.func
  misc/build.func
Labels: invalid

#1970 Fix: Increase HDD Space for Hoarder
  ct/hoarder.sh
  json/hoarder.json
Labels: website, update script

#1969 [Website] update data/page.tsx
  frontend/src/app/data/page.tsx
Labels: website

#1968 Update Script: urbackupserver.sh Include features during install
  ct/urbackupserver.sh
Labels: update script

#1975 [Standardization] Fix Spelling for "Setup Python3"
  install/lazylibrarian-install.sh
  install/metube-install.sh
  install/openwebui-install.sh
  install/paperless-ngx-install.sh
  install/spoolman-install.sh
Labels: update script

#1974 Feature: Clean Orphan LVM without CEPH
  misc/clean-orphaned-lvm.sh
Labels: update script

#1977 [Standardization]: Same Setup for GoLang on all LXC's & Clear Tarball
  install/authentik-install.sh
  install/caddy-install.sh
  install/memos-install.sh
  install/ollama-install.sh
  install/pocketid-install.sh
  install/rtsptoweb-install.sh
  install/sftpgo-install.sh
Labels: update script

#1955 New Script: Element Synapse
  ct/elementsynapse.sh
  install/elementsynapse-install.sh
  json/elementsynapse.json
Labels: website, new script

#1984 [Security & Maintenance] Update NodeJS Repo to 22 for new Installs
  ct/cronicle.sh
  install/adventurelog-install.sh
  install/archivebox-install.sh
  install/changedetection-install.sh
  install/dashy-install.sh
  install/flowiseai-install.sh
  install/frigate-install.sh
  install/ghost-install.sh
  install/grist-install.sh
  install/homepage-install.sh
  install/iobroker-install.sh
  install/linkwarden-install.sh
  install/mafl-install.sh
  install/magicmirror-install.sh
  install/matterbridge-install.sh
  install/memos-install.sh
  install/meshcentral-install.sh
  install/metube-install.sh
  install/monica-install.sh
  install/myspeed-install.sh
  install/n8n-install.sh
  install/node-red-install.sh
  install/openwebui-install.sh
  install/overseerr-install.sh
  install/pairdrop-install.sh
  install/part-db-install.sh
  install/peanut-install.sh
  install/pingvin-install.sh
  install/shinobi-install.sh
  install/tandoor-install.sh
  install/the-lounge-install.sh
  install/tianji-install.sh
  install/umami-install.sh
  install/uptimekuma-install.sh
  install/wikijs-install.sh
  install/zipline-install.sh
Labels: maintenance, update script

#1987 Update elementsynapse-install.sh
  install/elementsynapse-install.sh
Labels: invalid

#1925 New Script: Privatebin
  ct/privatebin.sh
  install/privatebin-install.sh
  json/privatebin.json
Labels: website, new script

#1994 Element Synapse sed fix
  install/elementsynapse-install.sh
Labels: update script

#1996 Fix: Monica Install with nodejs
  install/monica-install.sh
Labels: update script

#1999 Update build.func Fix Typo in Comment
  misc/build.func
Labels: invalid

#2006 Fix: Ghost LXC - Use Node20
  install/ghost-install.sh
Labels: update script

#2010 Update tandoor-install.sh, Fix node Version
  install/tandoor-install.sh
Labels: update script

#2011 Fix Tianji: Add heap-space value for nodejs
  ct/tianji.sh
Labels: update script

#2012 Proxmox Backup Server Renaming and Update fix
  ct/proxmox-backup-server.sh
  install/proxmox-backup-server-install.sh
  json/proxmox-backup-server.json
Labels: website, breaking change, rename script

#1990 [API] Masiv update to api
  frontend/src/app/data/page.tsx
  misc/api.func
  misc/build.func
  misc/install.func
Labels: website, maintenance, high risk

#2015 [Fix] Header breaks at long title - add width for figlet github action
  .github/workflows/scripts/generate-app-headers.sh
Labels: maintenance

#2017 [Fix]: Headername of Proxmox-Datacenter-Manager not in CamelCase
  ct/proxmox-datacenter-manager.sh
Labels: maintenance

#2020 Update authentik-install.sh
  install/authentik-install.sh
Labels: update script

#2022 Fix Script: post-pmg-install.sh
  misc/post-pmg-install.sh
Labels: update script

#2027 Fix actual update - missing hidden files, downloaded release cleanup
  ct/actualbudget.sh
Labels: update script

#2029 Fix header comments on contributor templates
  .github/CONTRIBUTOR_GUIDE/ct/AppName.sh
  .github/CONTRIBUTOR_GUIDE/install/AppName-install.sh
Labels: maintenance

#2040 [API] Add API backend code
  api/.env.example
  api/go.mod
  api/go.sum
  api/main.go
Labels: maintenance

#2038 Feature: Element Synapse: add option to enter server name during LXC installation
  install/elementsynapse-install.sh
Labels: update script

#2033 Bugfix: Jellyseerr pnpm Version
  ct/jellyseerr.sh
  install/jellyseerr-install.sh
Labels: update script

#1941 New Script: Radicale
  ct/radicale.sh
  install/radicale-install.sh
  json/radicale.json
Labels: website, new script

#2031 New script: Koillection
  ct/koillection.sh
  install/koillection-install.sh
  json/koillection.json
Labels: website, new script

#1926 New Script: Crafty-Controller
  ct/crafty-controller.sh
  install/crafty-controller-install.sh
  json/crafty-controller.json
Labels: website, new script

#2023 New Script: seelf
  ct/seelf.sh
  install/seelf-install.sh
  json/seelf.json
Labels: website, new script

#1928 New Script: Zerotier Controller
  ct/zerotier-one.sh
  install/zerotier-one-install.sh
  json/zerotier-one.json
Labels: website, new script

#2057 Update auto-update-app-headers.yml
  .github/workflows/auto-update-app-headers.yml
Labels: maintenance

#2049 [API] Update create-lxc.sh / Improve error messages #1
  .github/workflows/validate-filenames.yml
  ct/create_lxc.sh
Labels: maintenance, update script

#2070 Paperless NGX: Mark it as updateable
  json/paperless-ngx.json
Labels: website

#2072 Radicale: Provide additional information about configuration
  json/radicale.json
Labels: website

#2093 Add new LXC: Paperless-AI
  ct/paperless-ai.sh
  install/paperless-ai-install.sh
  json/paperless-ai.json
Labels: website, new script

#2067 Fix: Alpine IT-Tools Update
  ct/alpine-it-tools.sh
Labels: update script

#2100 Website: Update Footer for Json-Editor & Api
  frontend/src/components/Footer.tsx
Labels: website

#2079 New Script: Apache Tika
  ct/apache-tika.sh
  install/apache-tika-install.sh
  json/apache-tika.json
Labels: website, maintenance, high risk, new script

#2107 Website: Refactor Footer for improved layout and styling consistency
  frontend/src/components/Footer.tsx
Labels: website

#2106 Refactor JSON generator buttons layout for better alignment and consistency
  frontend/src/app/json-editor/page.tsx
Labels: website

#2052 New Script: Duplicati
  ct/duplicati.sh
  install/duplicati-install.sh
  json/duplicati.json
Labels: website, new script

#2113 Update auto-update-app-headers.yml
  .github/workflows/auto-update-app-headers.yml
Labels: invalid

#2121 Fix JSON-Editor
  frontend/src/app/json-editor/_components/InstallMethod.tsx
  frontend/src/app/json-editor/page.tsx
Labels: website

#2123 New Script: SearXNG
  ct/searxng.sh
  install/searxng-install.sh
  json/searxng.json
Labels: website, new script

#2120 New Script: Cosmos
  ct/cosmos.sh
  install/cosmos-install.sh
  json/cosmos.json
Labels: website, new script

#2127 Fix: PeaNUT Increase HDD & RAM Size
  ct/peanut.sh
  json/peanut.json
Labels: website, update script

#2132 Fix: Cosmos logo doesnt display on website
  json/cosmos.json
Labels: website

#2128 [core]: Enhance LXC template handling and improve error recovery
  ct/create_lxc.sh
Labels: maintenance, update script

#2137 Fix: Openwrt Version checking
  vm/openwrt.sh
Labels: update script

#2144 Fix: Zerotier json had a bad script path
  json/zerotier-one.json
Labels: website

#2148 Fix: Trillium Update Function & Harmonize Installation
  ct/trilium.sh
  install/trilium-install.sh
Labels: update script

#2162 Update cosmos.json description
  json/cosmos.json
Labels: website

#2167 New script: Barcode Buddy
  ct/barcode-buddy.sh
  install/barcode-buddy-install.sh
  json/barcode-buddy.json
Labels: website, new script

#2173 fix(actualbudget): Salvage the `.migrate` file when upgrading
  ct/actualbudget.sh
Labels: update script

#2174 fix typos in CONTRIBUTOR_GUIDE
  .github/CONTRIBUTOR_GUIDE/ct/AppName.md
  .github/CONTRIBUTOR_GUIDE/json/AppName.json
Labels: maintenance

#2175 Fix: AppName-install template remove duplicate lines
  .github/CONTRIBUTOR_GUIDE/install/AppName-install.sh
Labels: invalid, maintenance

#2160 Keep the same hass_config volume for Home Assistant
  ct/homeassistant.sh
Labels: update script

#2183 Fix: Barcode Buddy Logo & Title
  json/barcode-buddy.json
Labels: website

#2166 New Script: pbs_microcode.sh
  json/pbs-microcode.json
  misc/pbs_microcode.sh
Labels: website, new script

#2194 Website: Set new Logo for Paperless-AI
  json/paperless-ai.json
Labels: website

#2193 evcc.json Clarify the config file location
  json/evcc.json
Labels: website

#2021 [API] Add API to vms
  misc/api.func
  vm/archlinux-vm.sh
  vm/debian-vm.sh
  vm/docker-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/owncloud-vm.sh
  vm/pimox-haos-vm.sh
  vm/ubuntu2204-vm.sh
  vm/ubuntu2404-vm.sh
  vm/ubuntu2410-vm.sh
Labels: maintenance, update script

#2141 New Script: Zitadel
  ct/zitadel.sh
  install/zitadel-install.sh
  json/zitadel.json
Labels: website, new script

#2191 Fix: "read -p" does not support color formatting
  misc/build.func
Labels: maintenance, high risk

#2206 Fixed URL typo zerotier-one.json
  json/zerotier-one.json
Labels: website

#2203 [core] Prevent double spinner
  ct/create_lxc.sh
  misc/build.func
  misc/install.func
Labels: maintenance, high risk, update script

#2204 [core] Fix app-header workflow and add API
  .github/autolabeler-config.json
  .github/changelog-pr-config.json
  .github/workflows/auto-update-app-headers.yml
Labels: maintenance

#2211 Revert "[core] Prevent double spinner"
  ct/create_lxc.sh
  misc/build.func
  misc/install.func
Labels: invalid

#2207 [Fix] Filebrowser - Add Static Path for DB
  misc/filebrowser.sh
Labels: update script, breaking change

#2214 [gh]: Improve Workflows, Templates, Handling
  .github/DISCUSSION_TEMPLATE/request-script.yml
  .github/pull_request_template.md
  .github/workflows/autolabeler.yml
  .github/workflows/changelog-pr.yml
Labels: maintenance

#2199 Fix: Crafty-Controller java versions and set default
  install/crafty-controller-install.sh
Labels: update script

#2226 New Script: FreshRSS
  ct/freshrss.sh
  install/freshrss-install.sh
  json/freshrss.json
Labels: website, new script

#2228 Feature: Automatic Deletion of choosen LXC's (lxc-delete.sh)
  misc/lxc-delete.sh
Labels: update script

#1906 New Script: Proxmox Mail Gateway
  ct/proxmox-mail-gateway.sh
  install/proxmox-mail-gateway-install.sh
  json/proxmox-mail-gateway.json
Labels: website, new script

#2153 New Script: Prometheus Paperless-NGX Exporter
  ct/prometheus-paperless-ngx-exporter.sh
  install/prometheus-paperless-ngx-exporter-install.sh
  json/prometheus-paperless-ngx-exporter.json
Labels: website, new script

#2139 New Script: Suwayomi-Server
  ct/suwayomiserver.sh
  install/suwayomiserver-install.sh
  json/suwayomi-server.json
Labels: website, new script

#2243 New Script: Watcharr
  ct/watcharr.sh
  install/watcharr-install.sh
  json/watcharr.json
Labels: website, new script

#2258 Fix: Apache Guacamole Version Crawling - only latest Version
  install/apache-guacamole-install.sh
Labels: update script

#2266 Update pull_request_template.md: Remove unwanted dashes
  .github/pull_request_template.md
Labels: invalid

#2264 Update Checkmk: include Patch versions in Release grepping
  ct/checkmk.sh
  install/checkmk-install.sh
Labels: update script

#2269 Add Workflow to test Scripts
  .github/workflows/script-test.yml
  .github/workflows/scripts/app-test/pr-alpine-install.func
  .github/workflows/scripts/app-test/pr-build.func
  .github/workflows/scripts/app-test/pr-create-lxc.sh
  .github/workflows/scripts/app-test/pr-install.func
Labels: enhancement, nice to have, maintenance

#2097 New Script: Opnsense VM
  json/opnsense-vm.json
  vm/opnsense-vm.sh
Labels: website, new script

#2286 Quickfix: fix java default - crafty controller
  install/crafty-controller-install.sh
Labels: update script

#2282 Fix: SQL Server 2022 - remove unnecessary sudo
  install/sqlserver2022-install.sh
Labels: update script

#2291 Fix: Typo OPNsense VM
  vm/opnsense-vm.sh
Labels: update script

#2288 Frigate: Use Fixed Version 14
  install/frigate-install.sh
Labels: update script, breaking change

#2293 Fix: duplicate 'VM' name in opnsense-vm.json
  json/opnsense-vm.json
Labels: website

#2277 Fix changedetection: Correct Browser install
  install/changedetection-install.sh
Labels: update script

#2296 fix: frigate pin version
  install/frigate-install.sh
Labels: update script

#2302 Fix: Pingvin wrong variable used for version tracking
  ct/pingvin.sh
Labels: update script

#2308 Fix: Myspeed Installation (g++)
  install/myspeed-install.sh
Labels: update script

#2305 Update ubuntu2410-vm.sh: Fix typo in API call.
  vm/ubuntu2410-vm.sh
Labels: update script

#2307 Website: Add After-Install Note for Ubuntu VM 22.04/24.04/24.10 and Debian VM
  json/debian-vm.json
  json/ubuntu2204-vm.json
  json/ubuntu2404-vm.json
  json/ubuntu2410-vm.json
Labels: website

#2270 New Script: Graylog
  ct/graylog.sh
  install/graylog-install.sh
  json/graylog.json
Labels: website, new script

#2285 New Script: Excalidraw
  ct/excalidraw.sh
  install/excalidraw-install.sh
  json/excalidraw.json
Labels: website, new script

#2281 New Script: Kometa
  ct/kometa.sh
  install/kometa-install.sh
  json/kometa.json
Labels: website, new script

#2311 Fix: some jsons (debian instead Debian in OS)
  json/2fauth.json
  json/apache-guacamole.json
  json/firefly.json
  json/jenkins.json
  json/kimai.json
  json/komodo.json
  json/nextpvr.json
  json/onedev.json
  json/proxmox-datacenter-manager.json
  json/semaphore.json
  json/wallos.json
Labels: website

#2310 Fix: var_tags instead of TAGS in some CT's
  ct/2fauth.sh
  ct/apache-guacamole.sh
  ct/duplicati.sh
  ct/pocketid.sh
  ct/seelf.sh
  ct/suwayomiserver.sh
  ct/tasmocompiler.sh
  ct/watcharr.sh
  ct/zammad.sh
Labels: update script

#2318 Fix: Kometa - Fix wrong web site address
  ct/kometa.sh
  install/kometa-install.sh
  json/kometa.json
Labels: website, update script

#2325 Fix HomeAsisstant LXC: Use the latest versions of runlike with --use-volume-id
  ct/homeassistant.sh
Labels: update script

#2327 Bugfix: Authentik Embedded Outpost Upgrade
  ct/authentik.sh
Labels: update script

#2319 [gh] Workflow to change date on new json files
  .github/workflows/delete-json-branch.yml
  .github/workflows/update-json-date.yml
Labels: maintenance

#2333 New Script: MinIO
  ct/minio.sh
  install/minio-install.sh
  json/minio.json
Labels: website, new script

#2326 New Script: RustDesk Server
  ct/rustdeskserver.sh
  install/rustdeskserver-install.sh
  json/rustdeskserver.json
Labels: website, new script

#2342 Fix script category name text alignment in ScriptAccordion
  frontend/src/app/scripts/_components/ScriptAccordion.tsx
Labels: website

#2337 [GH] Remove unwanted output from script test workflow
  .github/workflows/script-test.yml
  .github/workflows/scripts/app-test/pr-build.func
  .github/workflows/scripts/app-test/pr-create-lxc.sh
  .github/workflows/scripts/app-test/pr-install.func
Labels: maintenance

#2347 Update script-test.yml
  .github/workflows/script-test.yml
Labels: invalid

#2358 Update build.func
  misc/build.func
Labels: maintenance, high risk

#2354 Update pr-build.func
  .github/workflows/scripts/app-test/pr-build.func
Labels: invalid

#2352 Fix: Zoraxy - now shows application as updateable on the website
  json/zoraxy.json
Labels: website

#2350 New Script: Nx Witness
  ct/nxwitness.sh
  install/nxwitness-install.sh
  json/nxwitness.json
Labels: website, new script

#2336 Re-Add: Pf2eTools
  ct/pf2etools.sh
  install/pf2etools-install.sh
  json/pf2etools.json
Labels: website, new script

#2376 Fix: Element Synapse - Fixed server listening on both localhost and 0.0.0.0
  install/elementsynapse-install.sh
Labels: update script

#2380 Missing ";" in ct/trilium.sh
  ct/trilium.sh
Labels: update script

#2377 [gh] Rework error Reporting in app-test workflow
  .github/workflows/scripts/app-test/pr-build.func
  .github/workflows/scripts/app-test/pr-install.func
Labels: invalid

#2389 Fix: RustDesk Server - Added configuration guide to json
  json/rustdeskserver.json
Labels: website

#2390 [API]Add more enpoints to API
  api/main.go
Labels: api

#2394 [gh] Introducing new Issue Github Template Feature (Bug, Feature, Task)
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/task.yml
Labels: maintenance

#2399 [gh] Update script-test.yml
  .github/workflows/script-test.yml
Labels: maintenance

#2411 Fix RustDesk slug in json
  json/rustdeskserver.json
Labels: bug

#2416 Fix: Homarr update service files
  ct/homarr.sh
Labels: update script

#2409 Update MagicMirror install and update scripts
  ct/magicmirror.sh
  install/magicmirror-install.sh
Labels: update script

#2415 [GH] Update script-test Workflow
  .github/workflows/script-test.yml
Labels: maintenance

#2412 Setup cron in install/freshrss-install.sh
  install/freshrss-install.sh
  json/freshrss.json
Labels: website, update script

#2428 Fix: Grist update no longer removes previous user data
  ct/grist.sh
Labels: update script

#2430 Fix: Typo in Ubuntu 24.10 VM Script
  vm/ubuntu2410-vm.sh
Labels: update script

#2434 Update Graylog icon
  json/graylog.json
Labels: website

#2433 Debian icon update
  json/debian-vm.json
  json/debian.json
Labels: website

#2444 Fix: Zipline increase SECRET to 42 chars
  install/zipline-install.sh
Labels: update script

#2455 Zipline: Prepare for Version 4.0.0
  ct/zipline.sh
  install/zipline-install.sh
Labels: update script, breaking change

#2466 Update BunkerWeb scripts to latest NGINX and specs
  ct/bunkerweb.sh
  install/bunkerweb-install.sh
  json/bunkerweb.json
Labels: website, update script

#2468 Fix: MagicMirror force Node version and fix backups
  ct/magicmirror.sh
Labels: update script

#2472 New Script: Docmost
  ct/docmost.sh
  install/docmost-install.sh
  json/docmost.json
Labels: website, new script

#2477 Feature: PBS Bare Metal Installation - Allow Microcode
  misc/pbs_microcode.sh
Labels: update script

#2476 Fix: SQL Server 2022 | GPG & Install
  install/sqlserver2022-install.sh
Labels: update script

#2494 Fix: Actual Budget, add missing .env when updating
  ct/actualbudget.sh
Labels: update script
