Repository community-scripts/ProxmoxVE, pull requests merged in 2025-01, with the labels that each got.

#1140 Fix chromium installation for ArchiveBox
  install/archivebox-install.sh
Labels: update script

#616 New Script: Firefly
  ct/firefly.sh
  install/firefly-install.sh
  json/firefly.json
Labels: website, new script

#1147 Update Kernel-Clean to new Version & Bugfixing
  misc/kernel-clean.sh
Labels: update script

#596 New Script: Semaphore
  ct/semaphore.sh
  install/semaphore-install.sh
  json/semaphore.json
Labels: website, new script

#1148 Fix Category of Semaphore
  json/semaphore.json
Labels: website

#1155 Fix Script Homepage: add version during build step
  ct/homepage.sh
  install/homepage-install.sh
Labels: update script

#1156 Correctly check for changed files in Shellcheck workflow
  .github/workflows/shellcheck.yml
Labels: maintenance

#1167 New Script: Komodo
  ct/komodo.sh
  install/komodo-install.sh
  json/komodo.json
Labels: website, new script

#1059 Update config template in blocky-install.sh
  install/blocky-install.sh
Labels: update script

#1191 Update Nextcloud-LXC JSON
  json/nextcloudpi.json
Labels: website

#1200 Keep Lubelogger data after update to a new version
  ct/lubelogger.sh
Labels: update script

#1207 Fix: Memos update function
  ct/memos.sh
Labels: update script

#1208 Improve Homarr Installation
  install/homarr-install.sh
Labels: update script

#1190 Update Script: Lazylibrarian
  install/lazylibrarian-install.sh
Labels: update script

#1110 Github action to check metadata lines in scripts.
  .github/workflows/check-metadata.yml
Labels: maintenance

#1213 Pf2eTools & 5eTools: Fixing npm build
  ct/5etools.sh
  ct/pf2etools.sh
  install/5etools-install.sh
  install/pf2etools-install.sh
Labels: update script

#1227 Fix: Update Python for HomeAssistant
  ct/homeassistant-core.sh
  install/homeassistant-core-install.sh
Labels: update script

#1228 [GitHub Action] Add filename case check
  .github/workflows/check-lowercase.yml
Labels: maintenance

#1238 Homarr: Fix missing curl dependency
  install/homarr-install.sh
Labels: update script

#1242 Fix gpg key pf2tools & 5etools
  install/5etools-install.sh
  install/pf2etools-install.sh
Labels: update script

#1221 [Breaking] Update Zigbee2mqtt to v.2.0.0 (Read PR Description)
  ct/zigbee2mqtt.sh
  install/zigbee2mqtt-install.sh
Labels: guide, update script, breaking change

#1261 Add RAM and Disk units
  misc/build.func
Labels: high risk

#1257 ci: combine header checks into workflow with PR comment
  .github/check-script.yml
  .github/workflows/check-metadata.yml
  .github/workflows/validate-scripts.yml
Labels: maintenance, update script

#1255 ci: change filename checks into steps with PR comment
  .github/workflows/check-lowercase.yml
  .github/workflows/validate-filenames.yml
Labels: maintenance, update script

#1216 Use profile.d to show the lxc details
  misc/alpine-install.func
  misc/install.func
Labels: high risk, update script

#1265 Check lxc maxkeys
  misc/build.func
Labels: high risk

#1239 ci: add pipeline for code formatting checks
  .github/workflows/validate-formatting.yaml
Labels: maintenance

#1279 Add reapproval of Changelog-PR
  .github/workflows/changelog-pr.yml
Labels: maintenance

#1282 Add ca-certificates for Install (Frigate)
  install/frigate-install.sh
Labels: update script

#1284 Fix: Homebox Update Script
  ct/homebox.sh
Labels: update script

#1285 fix: buffer from base64 in formatting pipeline
  .github/workflows/validate-formatting.yaml
Labels: maintenance, update script

#1292 [Fix]: Fixed rm Bug in pf2etools
  ct/pf2etools.sh
  install/pf2etools-install.sh
Labels: update script

#1201 New script: GLPI
  ct/glpi.sh
  install/glpi-install.sh
  json/glpi.json
Labels: website, new script

#1291 New Script: Typesense
  ct/typesense.sh
  install/typesense-install.sh
  json/typesense.json
Labels: website, new script

#1299 Fix Tag in HyperHDR Script
  ct/hyperhdr.sh
Labels: update script

#1309 Fix: Folder-Check for Updatescript Zammad
  ct/zammad.sh
Labels: update script

#1312 Set Execution Rights for GH-Action: Validate Scripts
  .github/workflows/validate-scripts.yml
Labels: maintenance

#1313 fix: make ssh authorized key default to empty string if unset
  misc/build.func
Labels: high risk

#1316 fix: permissions of validate pipelines
  .github/workflows/validate-filenames.yml
  .github/workflows/validate-formatting.yaml
  .github/workflows/validate-scripts.yml
Labels: maintenance

#1318 update postgresql json to add post install password setup
  json/postgresql.json
Labels: website

#1327 fix: correctly handle pull_request_target event
  .github/workflows/validate-filenames.yml
  .github/workflows/validate-formatting.yaml
  .github/workflows/validate-scripts.yml
Labels: maintenance

#1335 fix(ci): formatting event & chmod +x
  .github/workflows/validate-formatting.yaml
  .github/workflows/validate-scripts.yml
Labels: maintenance

#1344 fix: only validate scripts in validate-scripts workflow
  .github/workflows/validate-scripts.yml
Labels: maintenance

#1334 Fix: AdventureLog - update script bug
  ct/adventurelog.sh
Labels: update script

#960 New Script: calibre-server
  ct/calibre-server.sh
  install/calibre-server-install.sh
  json/calibre-server.json
Labels: website, new script

#1198 New script: ps5-mqtt
  ct/ps5-mqtt.sh
  install/ps5-mqtt-install.sh
  json/ps5-mqtt.json
Labels: website, new script

#1272 New Script: Prometheus Alertmanager
  ct/prometheus-alertmanager.sh
  install/prometheus-alertmanager-install.sh
  json/prometheus-alertmanager.json
Labels: website, new script

#1254 Install/update ActualBudget based on releases, not latest master
  ct/actualbudget.sh
  install/actualbudget-install.sh
Labels: update script

#1301 Update rest of build func
  misc/build.func
Labels: update script

#1359 Update calibre-server-install.sh
  install/calibre-server-install.sh
Labels: update script

#1362 Delete calibre
  ct/calibre-server.sh
  install/calibre-server-install.sh
  json/calibre-server.json
Labels: website, breaking change, delete script

#1370 Fix: AdventureLog: unzip to /opt/
  ct/adventurelog.sh
Labels: update script

#1376 Fix: ActualBudget Update-Function
  ct/actualbudget.sh
  install/actualbudget-install.sh
Labels: update script

#1379 Update nzbget.json
  json/nzbget.json
Labels: website

#920 Add initial PR for Contributing & Coding Standard
  .github/CONTRIBUTING.md
  .github/CONTRIBUTOR_GUIDE/ct/AppName.md
  .github/CONTRIBUTOR_GUIDE/ct/AppName.sh
  .github/CONTRIBUTOR_GUIDE/install/AppName-install.md
  .github/CONTRIBUTOR_GUIDE/install/AppName-install.sh
  .github/CONTRIBUTOR_GUIDE/json/AppName.json
  .github/CONTRIBUTOR_GUIDE/json/AppName.md
Labels: documentation, investigation, guide, maintenance

#1382 [Core] add Github Action for Generate AppHeaders (figlet remove part 1)
  .github/workflows/generate-app-headers.sh
  .github/workflows/generate-app-headers.yaml
Labels: maintenance

#1385 Fix checkmk-install.sh: Version crawling.
  install/checkmk-install.sh
Labels: update script

#1384 [core]: add support for custom tags
  misc/build.func
Labels: nice to have, high risk, update script

#1395 [core]: check json date of new prs & update it
  .github/workflows/check_and_update_json_date.yml
Labels: maintenance

#1361 New script : Ghost
  ct/ghost.sh
  install/ghost-install.sh
  json/ghost.json
Labels: website, new script

#1403 Update komodo.sh: Fix broken paths in update_script().
  ct/komodo.sh
Labels: update script

#1398 Visual Studio Code: Set Workspace recommended extensions
  .vscode/extensions.json
Labels: documentation, guide, maintenance

#1402 Update Prometheus + Alertmanager: Unify scripts for easier maintenance
  ct/prometheus-alertmanager.sh
  ct/prometheus.sh
  install/prometheus-install.sh
Labels: update script

#1399 Update check_and_update_json_date.yml: Change path to /json
  .github/workflows/check_and_update_json_date.yml
Labels: maintenance

#1408 Fix user in ghost-cli install command
  install/ghost-install.sh
Labels: update script

#1416 Prometheus: Fix installation via creating the service file
  install/prometheus-install.sh
Labels: update script

#1418 Update prometheus-alertmanager-install.sh: Service Creation Fix
  install/prometheus-alertmanager-install.sh
Labels: update script

#1417 Update prometheus-install.sh: Service creation fix
  install/prometheus-install.sh
Labels: update script

#1444 Fix inexistent folder on actualbudget update script
  ct/actualbudget.sh
Labels: update script

#1423 GitHub Actions: Fix Shellsheck workflow to only run on changes `*.sh` files
  .github/workflows/shellcheck.yml
Labels: maintenance

#1456 feat: allow adding SSH authorized key for root (advanced settings) by @dsiebel
  misc/build.func
Labels: high risk

#1325 Update Hoarder: Improvement .env location (see PR comment for little migration)
  ct/hoarder.sh
  install/hoarder-install.sh
Labels: update script, breaking change

#1429 New Script: Opengist
  ct/opengist.sh
  install/opengist-install.sh
  json/opengist.json
Labels: website, new script

#1471 Update opengist-install.sh: Add git as dependencie
  install/opengist-install.sh
Labels: update script

#1473 [core] Update build.func: Fix bug with advanced tags
  misc/build.func
Labels: high risk

#1466 [website] Update footer text
  frontend/src/components/Footer.tsx
Labels: website

#1480 Update tianji-install.sh: Add OPENAI_API_KEY to .env
  install/tianji-install.sh
Labels: update script, breaking change

#1485 New Script: Wordpress
  ct/wordpress.sh
  install/wordpress-install.sh
  json/wordpress.json
Labels: website, new script

#1492 Hotfix build.func: Error when tags are empty
  misc/build.func
Labels: maintenance, high risk

#1497 Fix: Add FFMPEG for OpenWebUI
  install/openwebui-install.sh
Labels: update script

#1502 [core] build.func&install.func: Fix ssh keynot added error
  misc/build.func
  misc/install.func
Labels: maintenance, high risk

#1503 New script: phpIPAM
  ct/phpipam.sh
  install/phpipam-install.sh
  json/phpipam.json
Labels: website, new script

#1523 [core] Recreate Update JSON Workflow
  .github/workflows/update_json_date.yml
Labels: maintenance

#1526 [core]Update update_json_date.yml
  .github/workflows/update_json_date.yml
Labels: maintenance

#1525 [Workflow]Update autolabeler-config.json
  .github/autolabeler-config.json
Labels: maintenance

#1533 Website: Fix "Scripts by TTeck": Typo & Mobile View
  frontend/src/app/page.tsx
Labels: website

#1501 New script: Dotnet ASP.NET Web Server
  ct/dotnetaspwebapi.sh
  install/dotnetaspwebapi-install.sh
  json/dotnetaspwebapi.json
Labels: website, new script

#1540 Update Openwrt: Delete lines that do WAN input and forward accept
  vm/openwrt.sh
Labels: update script, breaking change

#1545 Update apt-cacher-ng.sh: Typo/Missing $
  ct/apt-cacher-ng.sh
Labels: update script

#1562 Update VM Tags
  vm/debian-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/owncloud-vm.sh
  vm/ubuntu2204-vm.sh
  vm/ubuntu2404-vm.sh
Labels: update script

#1565 Fix linkwarden update
  ct/linkwarden.sh
Labels: update script

#1563 [jellyseerr] Update nodejs if not up-to-date
  ct/jellyseerr.sh
Labels: update script

#1550 breaking change: homeassistant upgrade os and python3
  ct/homeassistant-core.sh
  install/homeassistant-core-install.sh
  json/homeassistant-core.json
Labels: website, update script, breaking change

#1572 Update Opengist.sh: Fix broken backup function
  ct/opengist.sh
  json/opengist.json
Labels: website, update script

#1597 Fix Pocketbase URL after install
  ct/pocketbase.sh
Labels: update script

#1559 New Script: Proxmox Mail Gateway Post Installer
  json/post-pmg-install.json
  misc/post-pmg-install.sh
Labels: website, new script

#1602 Add new Check for LXC MaxKeys by @cricalix
  misc/build.func
Labels: maintenance, high risk

#1601 Unifi.sh fix wrong URL after Install
  ct/unifi.sh
Labels: update script

#1603 Grafana: Mark container as updateable
  json/grafana.json
Labels: website

#1569 New Script: UrBackup Server
  ct/urbackupserver.sh
  install/urbackupserver-install.sh
  json/urbackupserver.json
Labels: website, new script

#1613 Feature: Add xCaddy for external Modules on Caddy-LXC
  ct/caddy.sh
  install/caddy-install.sh
  json/caddy.json
Labels: website, update script

#1548 [core] Update build.func: Add defaults to Advanced mode
  misc/build.func
Labels: maintenance, high risk

#1616 New script: ProjectSend
  ct/projectsend.sh
  install/projectsend-install.sh
  json/projectsend.json
Labels: website, new script

#1482 New script: SQL Server 2022
  ct/sqlserver2022.sh
  install/sqlserver2022-install.sh
  json/sqlserver2022.json
Labels: website, new script

#1608 New Script: Docker VM
  json/docker-vm.json
  vm/docker-vm.sh
Labels: website, new script

#1619 New Script: Beszel
  ct/beszel.sh
  install/beszel-install.sh
  json/beszel.json
Labels: website, new script

#1629 PBS.sh: Fix wrong URL after Setup
  ct/pbs.sh
Labels: update script

#1630 Fix Docker-VM name on website
  json/docker-vm.json
Labels: website

#1633 Update MOTD: Add Dynamic IP with profile.d by @JcMinarro
  misc/alpine-install.func
  misc/install.func
Labels: maintenance, high risk, update script

#1636 Add new Script: LXC Delete (Proxmox)
  json/lxc-delete.json
  misc/lxc-delete.sh
Labels: website, new script

#1639 Fix Photoprism missing folder & environments
  install/photoprism-install.sh
Labels: update script

#1643 ActualBudget: Fix Update-Function, Fix Wget Crawling, Add Versionscheck
  ct/actualbudget.sh
  install/actualbudget-install.sh
Labels: update script

#1649 Fix: Docker VM deprecated gpg
  vm/docker-vm.sh
Labels: update script

#1659 Moving SQL Server 2022 to database category
  json/sqlserver2022.json
Labels: website

#1669 Fix: SQL Server 2022 Install
  install/sqlserver2022-install.sh
  json/sqlserver2022.json
Labels: website, update script

#1656 Tweak: LubeLogger Script Upcoming Changes 1.4.3
  ct/lubelogger.sh
Labels: update script

#1667 Add Docker-VM to Containers & Docker Category
  json/docker-vm.json
Labels: website

#1679 Refactor various components and configuration for mobile responsiveness.
  frontend/src/app/page.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/config/siteConfig.tsx
Labels: website

#1681 Refactor Sidebar component to display unique scripts count
  frontend/src/app/scripts/_components/Sidebar.tsx
Labels: website

#1688 Fix: Paperless Service Timings & Optimization: Ghostscript Installation
  install/paperless-ngx-install.sh
Labels: update script

#1695 Feature: Add Debian Disk Size / Redesign / Increase Disk
  vm/debian-vm.sh
Labels: update script

#1697 Refactor ScriptInfoBlocks and siteConfig to properly show the most populair scripts
  frontend/src/app/scripts/_components/ScriptInfoBlocks.tsx
  frontend/src/config/siteConfig.tsx
Labels: website

#1701 Update build.func: Ubuntu advanced settings version
  misc/build.func
Labels: maintenance, high risk

#1711 New Script: Ubuntu 24.10 VM
  json/ubuntu2410-vm.json
  vm/ubuntu2410-vm.sh
Labels: website, new script

#1714 Feature: Ubuntu 24.04 VM > Redesign | Optional HDD-Size Prompt | cifs support
  json/ubuntu2404-vm.json
  vm/ubuntu2404-vm.sh
Labels: website, update script

#1712 Feature: Ubuntu 22.04 VM > Redesign | Optional HDD-Size Prompt
  json/ubuntu2204-vm.json
  vm/ubuntu2204-vm.sh
Labels: website, update script

#1716 Feature: Filebrowser Script > Redesign | Update Logic | Remove Logic
  misc/filebrowser.sh
Labels: update script

#1719 [Core] Better Creation of App Headers for next feature
  .github/workflows/auto-update-app-headers.yml
  .github/workflows/scripts/generate-app-headers.sh
Labels: maintenance

#1734 openHAB - Update to Zulu21
  ct/openhab.sh
  install/openhab-install.sh
Labels: update script

#1755 Added environment variable to accept EULA for SQLServer2022
  install/sqlserver2022-install.sh
Labels: update script

#1762 Fix the command to create new users
  json/the-lounge.json
Labels: website

#1763 Calibre-Web: added installation of calibre binaries
  install/calibre-web-install.sh
Labels: update script

#1766 openHAB - Use https and include doc url
  ct/openhab.sh
  json/openhab.json
Labels: website, update script

#1768 Jellyfin: Fix default logging level
  install/jellyfin-install.sh
Labels: update script

#1771 Fix jellyfin update command
  ct/jellyfin.sh
Labels: update script

#1780 New Script: Arch Linux VM
  json/archlinux-vm.json
  vm/archlinux-vm.sh
Labels: website, new script

#1782 Update archlinux-vm.json
  json/archlinux-vm.json
Labels: website

#1789 Update frontend alpine-vaultwarden hdd size and OS version
  json/vaultwarden.json
Labels: website

#1802 [core]: Remove Figlet | Get Headers by Repo & Store Local
  misc/build.func
Labels: maintenance, high risk

#1803 Update all Alpine LXC's to 3.21 (Docker, Grafana, Nextcloud, Vaultwarden, Zigbee2Mqtt, Alpine)
  ct/alpine-docker.sh
  ct/alpine-grafana.sh
  ct/alpine-nextcloud.sh
  ct/alpine-vaultwarden.sh
  ct/alpine-zigbee2mqtt.sh
  ct/alpine.sh
  json/alpine.json
  json/docker.json
  json/grafana.json
  json/nextcloudpi.json
  json/vaultwarden.json
  json/zigbee2mqtt.json
Labels: website, update script

#1779 New Script: Pocket ID
  ct/pocketid.sh
  install/pocketid-install.sh
  json/pocketid.json
Labels: website, new script

#1809 [docs] Update AppName.md: Make it clear where to change the URLs
  .github/CONTRIBUTOR_GUIDE/ct/AppName.md
Labels: maintenance

#1810 [Standardization] Fix Spelling for "Setup Python3"
  install/bazarr-install.sh
  install/changedetection-install.sh
  install/deluge-install.sh
  install/esphome-install.sh
  install/frigate-install.sh
  install/homeassistant-core-install.sh
  install/homeassistant-install.sh
  install/motioneye-install.sh
  install/mylar3-install.sh
  install/octoprint-install.sh
  install/sabnzbd-install.sh
  install/tandoor-install.sh
  install/tautulli-install.sh
  install/whoogle-install.sh
Labels: maintenance, update script

#1811 New Script: NodeBB
  ct/nodebb.sh
  install/nodebb-install.sh
  json/nodebb.json
Labels: website, new script

#1813 New script: Monica LXC
  ct/monica.sh
  install/monica-install.sh
  json/monica.json
Labels: website, new script

#1819 Update pingvin.sh and pingvin-install.sh: Fix problem with update und switch to new method of getting files.
  ct/pingvin.sh
  install/pingvin-install.sh
Labels: update script

#1825 Breaking Change: Homarr v1 (Read Guide)
  ct/homarr.sh
  install/homarr-install.sh
Labels: update script, breaking change

#1828 Filter out duplicate scripts in LatestScripts component and sort by creation date
  frontend/src/app/scripts/_components/ScriptInfoBlocks.tsx
Labels: website

#1838 New Script: Clean Orphaned LVM
  json/clean-orphaned-lvm.json
  misc/clean-orphaned-lvm.sh
Labels: website, new script

#1843 Update clean-orphaned-lvm.json
  json/clean-orphaned-lvm.json
Labels: website
