Repository community-scripts/ProxmoxVE, pull requests merged in 2025-10, with the labels that each got.

#7994 Immich: bump version to 1.144.1
  ct/immich.sh
  install/immich-install.sh
Labels: update script, refactor

#8060 grist: remove unneeded var
  install/grist-install.sh
Labels: update script, bugfix

#8071 Remove Petio Script
  ct/petio.sh
  frontend/public/json/petio.json
  install/petio-install.sh
Labels: breaking change, delete script

#8074 GLPI: Fix database setup
  install/glpi-install.sh
Labels: update script, bugfix

#8087 Adjust navbar layout for large screen
  frontend/src/components/navbar.tsx
Labels: website, bugfix

#8090 Immich: bump version to 2.0.1
  ct/immich.sh
  install/immich-install.sh
Labels: update script, refactor

#8092 GLPI: Pin version to v10.0.20
  install/glpi-install.sh
Labels: update script, bugfix

#8103 PosgreSQL: Add version choice
  frontend/public/json/postgresql.json
  install/alpine-postgresql-install.sh
  install/postgresql-install.sh
Labels: update script, feature, json

#8113 fix: pve-scripts-local: typo
  ct/pve-scripts-local.sh
Labels: invalid, update script, refactor

#8119 Update cockpit to Debian 13
  ct/cockpit.sh
  frontend/public/json/cockpit.json
  install/cockpit-install.sh
Labels: update script, feature, json

#8125 AdventureLog: bump to debian 13
  ct/adventurelog.sh
  frontend/public/json/adventurelog.json
  install/adventurelog-install.sh
Labels: update script, feature, json

#8140 NocoDB: bump to Debian 13
  ct/nocodb.sh
  frontend/public/json/nocodb.json
  install/nocodb-install.sh
Labels: update script, feature, json

#8148 GLPI: Revert fix for v11
  install/glpi-install.sh
Labels: update script, bugfix

#8158 Docmost: Fixes and updates
  ct/docmost.sh
  frontend/public/json/docmost.json
  install/docmost-install.sh
Labels: update script, feature, json

#8160 Alpine-Wireguard: Fix for update failing in normal mode
  ct/alpine-wireguard.sh
Labels: update script, bugfix

#8173 Palmr: Fix NodeJS setup
  install/palmr-install.sh
Labels: update script, bugfix

#8174 Bump Z-Y Scripts to Debian 13
  ct/yt-dlp-webui.sh
  ct/zammad.sh
  ct/zerotier-one.sh
  ct/zigbee2mqtt.sh
  ct/zipline.sh
  ct/zitadel.sh
  ct/zoraxy.sh
  ct/zot-registry.sh
  ct/zwave-js-ui.sh
  frontend/public/json/yt-dlp-webui.json
  frontend/public/json/zammad.json
  frontend/public/json/zerotier-one.json
  frontend/public/json/zigbee2mqtt.json
  frontend/public/json/zipline.json
  frontend/public/json/zitadel.json
  frontend/public/json/zoraxy.json
  frontend/public/json/zot-registry.json
  frontend/public/json/zwave-js-ui.json
  install/yt-dlp-webui-install.sh
  install/zammad-install.sh
  install/zerotier-one-install.sh
  install/zigbee2mqtt-install.sh
  install/zipline-install.sh
  install/zitadel-install.sh
  install/zoraxy-install.sh
  install/zot-registry-install.sh
  install/zwave-js-ui-install.sh
Labels: update script, feature, json

#8199 MyIP: Increase resources
  ct/myip.sh
  frontend/public/json/myip.json
Labels: update script, json
