Repository community-scripts/ProxmoxVE, pull requests merged in 2025-07, with the labels that each got.

#5640 Changedetection: Base64 encode the launch options
  install/changedetection-install.sh
Labels: update script, bugfix

#5636 Remove: Readarr
  frontend/public/json/readarr.json
Labels: website, breaking change

#5635 Remove: Pingvin-Share
  frontend/public/json/pingvin.json
Labels: website, breaking change

#5661 qBittorrent: Add additional check before moving the config directory
  ct/qbittorrent.sh
Labels: invalid, update script, bugfix

#5662 Zipline: Fix typo in uploads directory path
  ct/zipline.sh
  install/zipline-install.sh
Labels: update script, bugfix

#5659 Bump Icons to selfhst repo | switch svg to webp
  frontend/public/json/add-iptag.json
  frontend/public/json/babybuddy.json
  frontend/public/json/convertx.json
  frontend/public/json/huntarr.json
  frontend/public/json/itsm-ng.json
  frontend/public/json/librespeed-rust.json
  frontend/public/json/lyrionmusicserver.json
  frontend/public/json/oauth2-proxy.json
  frontend/public/json/pulse.json
  frontend/public/json/rclone.json
  frontend/public/json/streamlink-webui.json
Labels: website, json

#5665 Refactor: Trilium
  ct/trilium.sh
  frontend/public/json/trilium.json
  install/trilium-install.sh
Labels: website, update script, json, refactor

#5685 ESPHome: Fix Linking issue to prevent version mismatch
  ct/esphome.sh
  install/esphome-install.sh
Labels: update script, bugfix

#5690 Komodo: Update Script to use FerretDB / remove psql & sqlite options
  ct/alpine-komodo.sh
  ct/komodo.sh
  install/alpine-komodo-install.sh
  install/komodo-install.sh
Labels: update script, breaking change, bugfix

#5688 Outline: Fix sed command for v0.85.0
  install/outline-install.sh
Labels: update script, bugfix

#5705 Core layer refactor: centralized error traps and msg_* consistency
  misc/alpine-install.func
  misc/build.func
  misc/core.func
  misc/create_lxc.sh
  misc/install.func
  misc/tools.func
Labels: maintenance, high risk, update script, core

#5715 Mafl: Fix moving of backed up data
  ct/mafl.sh
Labels: invalid, update script, bugfix

#5726 Refactor: AgentDVR
  install/agentdvr-install.sh
Labels: update script, refactor

#5722 Refactor: Authelia
  ct/authelia.sh
  install/authelia-install.sh
Labels: update script, refactor

#5723 Refactor: Dashy
  ct/dashy.sh
  install/dashy-install.sh
Labels: update script, refactor

#5724 Refactor: CryptPad
  ct/cryptpad.sh
  install/cryptpad-install.sh
Labels: update script, refactor

#5725 Refactor: ByteStash
  ct/bytestash.sh
  install/bytestash-install.sh
Labels: update script, refactor

#5732 Refactor: BookStack
  ct/bookstack.sh
  install/bookstack-install.sh
Labels: update script, refactor

#5743 Resolves incorrect URL at end of Pocket ID script
  ct/pocketid.sh
Labels: update script, bugfix

#5736 Refactor: Baikal
  ct/baikal.sh
  install/baikal-install.sh
Labels: update script, refactor

#5735 Refactor: Barcodebuddy
  ct/barcode-buddy.sh
  install/barcode-buddy-install.sh
Labels: update script

#5733 Refactor: Bitmagnet
  ct/bitmagnet.sh
  install/bitmagnet-install.sh
Labels: update script, refactor

#5716 [Feature] Add option to expose Docker via TCP port (alpine docker)
  install/alpine-docker-install.sh
  install/docker-install.sh
Labels: update script, feature

#5770 EMQX: Add warning to website
  frontend/public/json/emqx.json
Labels: website, json

#5773 Dockge: Mark updateable on website
  frontend/public/json/dockge.json
Labels: invalid, website, json

#5707 Refactor: Changed the way we install BunkerWeb by leveraging the brand new install-bunkerweb.sh
  ct/bunkerweb.sh
  frontend/public/json/bunkerweb.json
  install/bunkerweb-install.sh
Labels: update script, refactor

#5779 Bookstack: Fix PHP Issue & Bump to PHP 8.3
  ct/bookstack.sh
  install/bookstack-install.sh
  misc/tools.func
Labels: update script, bugfix

#5780 tools.func: add AVX check for MongoDB
  misc/tools.func
Labels: update script, feature

#5781 tools.func: better handling when unpacking tarfiles in prebuild mode
  misc/tools.func
Labels: maintenance, update script, feature, core

#5783 Refactor: Threadfin (+ updatable)
  ct/threadfin.sh
  frontend/public/json/threadfin.json
  install/threadfin-install.sh
Labels: update script, feature

#5791 IP-Tag: Optimizations / Guide / Manual Execution
  frontend/public/json/add-iptag.json
  tools/pve/add-iptag.sh
Labels: pve-tool

#5807 Fix unbound var in pulse.sh
  ct/pulse.sh
Labels: update script

#5811 Tinyauth: Fix LXC autologin
  install/alpine-tinyauth-install.sh
Labels: invalid, update script

#5812 fix func order
  install/alpine-tinyauth-install.sh
Labels: invalid, update script

#5825 BookStack: Fix enabling of php module
  install/bookstack-install.sh
Labels: invalid, update script

#5835 Refactor: ErsatzTV
  ct/ersatztv.sh
  frontend/public/json/ersatztv.json
  install/ersatztv-install.sh
Labels: update script, refactor

#5849 Refactor: gatus
  ct/gatus.sh
  install/gatus-install.sh
Labels: update script, refactor

#5841 Refactor: Excalidraw
  ct/excalidraw.sh
  install/excalidraw-install.sh
Labels: update script, refactor

#5856 BabyBuddy: fix path issues for update
  ct/babybuddy.sh
Labels: update script, bugfix

#5847 Refactor: FreshRSS
  install/freshrss-install.sh
Labels: update script, refactor

#5865 tools.func: strip leading folders for prebuild assets
  misc/tools.func
Labels: update script, feature, core

#5802 Refactor: Commafeed
  ct/commafeed.sh
  install/commafeed-install.sh
Labels: update script, feature, refactor

#5876 Refactor: Gitea
  ct/gitea.sh
  install/gitea-install.sh
Labels: update script, refactor

#5845 Refactor: FlareSolverr
  ct/flaresolverr.sh
  install/flaresolverr-install.sh
Labels: update script, refactor

#5875 core: Fix VAAPI passthrough for unprivileged LXC containers via devX
  misc/build.func
  misc/core.func
Labels: update script, bugfix, core

#5874 Refactor: Glance
  ct/glance.sh
  install/glance-install.sh
Labels: update script, refactor

#5872 Refactor: Stirling-PDF
  ct/stirling-pdf.sh
  frontend/public/json/stirling-pdf.json
  install/stirling-pdf-install.sh
Labels: update script, breaking change, json, refactor

#5886 FreshRSS: fix needed php modules
  install/freshrss-install.sh
Labels: update script, bugfix

#5891 Baikal: Fix PHP dependencies
  install/baikal-install.sh
Labels: invalid, update script, bugfix

#5894 Omada Update: add missing exit
  ct/omada.sh
Labels: update script, bugfix

#5907 Refactor: EMQX + Update-Function + Improved NodeJS Crawling
  ct/emqx.sh
  frontend/public/json/emqx.json
  install/emqx-install.sh
  misc/tools.func
Labels: update script, json, core, refactor

#5911 Refactor: Habitica
  ct/habitica.sh
  frontend/public/json/habitica.json
  install/habitica-install.sh
Labels: update script, json

#5896 Immich: handle custom library dependency updates; other fixes
  ct/immich.sh
  install/immich-install.sh
Labels: update script, refactor

#5889 Refactor & Function Bump: Docker
  ct/docker.sh
  install/docker-install.sh
Labels: update script, feature

#5940 Barcode-Buddy: Fix PHP module list
  install/barcode-buddy-install.sh
Labels: invalid, update script, bugfix

#5954 Update nic-offloading-fix: add Intel as search Text
  frontend/public/json/nic-offloading-fix.json
Labels: website, json

#5965 Revert from Self Hosted to Ubunut-latest for actions
  .github/workflows/auto-update-app-headers.yml
  .github/workflows/autolabeler.yml
  .github/workflows/changelog-pr.yml
  .github/workflows/crawl-versions.yaml
  .github/workflows/delete-json-branch.yml
  .github/workflows/frontend-cicd.yml
  .github/workflows/github-release.yml
  .github/workflows/update-json-date.yml
Labels: invalid

#5974 Dashy: remove unbound variable (RELEASE)
  install/dashy-install.sh
Labels: update script, bugfix

#5957 add --break-system-packages certbot-dns-cloudflare to the nginxproxym…
  ct/nginxproxymanager.sh
Labels: update script, bugfix

#6002 Refactor: PeaNUT
  ct/peanut.sh
  frontend/public/json/peanut.json
  install/peanut-install.sh
Labels: update script, json, refactor

#5998 2FAuth: Improve Update-Check
  ct/2fauth.sh
  install/2fauth-install.sh
Labels: update script, bugfix

#6051 Reactive Resume: switch source to community-maintained fork
  ct/reactive-resume.sh
  frontend/public/json/reactive-resume.json
  install/reactive-resume-install.sh
Labels: update script, json

#6066 AdventureLog: add backup folder before update
  ct/adventurelog.sh
Labels: update script, bugfix

#6080 Update cloudreve - config path
  frontend/public/json/cloudreve.json
Labels: bugfix, json

#6084 Fixed nag script on ProxMox 8.4.5
  tools/pve/post-pve-install.sh
Labels: update script, pve-tool

#6093 Fix OpenWebUI install/update scripts
  ct/openwebui.sh
  install/openwebui-install.sh
Labels: update script, bugfix

#6119 firefly: fix permissions at update
  ct/firefly.sh
Labels: update script, bugfix

#6133 wallos: add cron in installer for yearly cost
  ct/wallos.sh
  install/wallos-install.sh
Labels: update script, feature

#6139 fix(nginxproxymanager.sh): Set the version number before build.
  ct/nginxproxymanager.sh
Labels: update script, breaking change, bugfix

#6141 [core]: tools.func: increase setup_php function
  misc/tools.func
Labels: update script, core, refactor

#6142 [core]: Improved LXC Container Startup Handling
  misc/build.func
Labels: update script, feature, core

#6156 tools.func - fix typo for target_file
  misc/tools.func
Labels: update script, core

#6162 Fixed the previous fix of the anti-nag hook and propagated fixes everywhere
  tools/pve/post-pbs-install.sh
  tools/pve/post-pmg-install.sh
  tools/pve/post-pve-install.sh
Labels: update script, pve-tool

#6197 Refactor: Gokapi
  ct/gokapi.sh
  install/gokapi-install.sh
Labels: update script, refactor

#6217 SnipeIT - Update dependencies
  install/snipeit-install.sh
Labels: update script, feature

#6221 Wizarr: use absolute path to uv
  ct/wizarr.sh
  install/wizarr-install.sh
Labels: update script, bugfix

#6219 Immich v1.136.0
  ct/immich.sh
  install/immich-install.sh
Labels: update script, breaking change, bugfix

#6235 Pulse: Change note for API-Key Generation
  frontend/public/json/pulse.json
Labels: bugfix, json

#6237 Alpine TeamSpeak Server: Fix RELEASE fetch
  ct/alpine-teamspeak-server.sh
  install/alpine-teamspeak-server-install.sh
Labels: invalid, update script, bugfix

#6243 Immich: fix #6236
  install/immich-install.sh
Labels: update script, bugfix

#6251 PiAlert: Update dependencies
  install/pialert-install.sh
Labels: update script, bugfix

#6259 OnlyOffice: move to correct category
  frontend/public/json/onlyoffice.json
Labels: json

#6266 Remove Opensense VM for the moment
  frontend/public/json/opnsense-vm.json
Labels: breaking change

#6280 go2rtc: Fix release download handling
  install/go2rtc-install.sh
Labels: update script, bugfix

#6283 karakeep: export DATA_DIR from user config in update
  ct/karakeep.sh
Labels: update script, feature, bugfix

#6285 karakeep: Run workers in prod without tsx
  ct/karakeep.sh
  install/karakeep-install.sh
Labels: update script, feature

#6293 add 'g++' to actualbudget-install.sh
  install/actualbudget-install.sh
Labels: update script, bugfix

#6177 fix: removing ",gw=" from GATE var when reading/writing from/to config.
  misc/build.func
  misc/config-file.func
Labels: update script, bugfix, core

#6301 Refactor: Gotify
  ct/gotify.sh
  frontend/public/json/gotify.json
  install/gotify-install.sh
  misc/tools.func
Labels: update script, json, core, refactor

#6316 fix: SSH authorized keys not added in Alpine install script
  misc/alpine-install.func
Labels: update script, bugfix, core

#6314 Refactor: Cronicle
  ct/cronicle.sh
  frontend/public/json/cronicle.json
  install/cronicle-install.sh
Labels: update script, json

#6330 Element Synapse CT RAM increased from 1024 to 2048
  ct/elementsynapse.sh
  frontend/public/json/elementsynapse.json
Labels: update script, bugfix, json

#6335 Refactor: Photoprism
  ct/photoprism.sh
  install/photoprism-install.sh
Labels: update script, refactor

#6322 Update keycloak script to support configuration of latest release (v26)
  ct/keycloak.sh
  frontend/public/json/keycloak.json
  install/keycloak-install.sh
Labels: update script, json, refactor

#6344 Refactor: Jackett
  ct/jackett.sh
  frontend/public/json/jackett.json
  install/jackett-install.sh
Labels: update script, json, refactor

#6338 Refactor: HomeBox
  ct/homebox.sh
  frontend/public/json/homebox.json
  install/homebox-install.sh
Labels: update script, json, refactor

#6357 Salt: Remove interface port from website
  frontend/public/json/salt.json
Labels: json

#6380 Habitica: Fix trusted domains
  install/habitica-install.sh
Labels: update script, bugfix

#6374 Refactor: Komga
  ct/komga.sh
  install/komga-install.sh
Labels: update script, refactor

#6379 Refactor: Lidarr
  ct/lidarr.sh
  frontend/public/json/lidarr.json
  install/lidarr-install.sh
Labels: update script, json

#6378 Librespeed-Rust: Fix service name and RELEASE var fetching
  ct/librespeed-rust.sh
  install/librespeed-rust-install.sh
Labels: update script, bugfix

#6356 Strip SD and NS prefixes before writing to config file
  misc/build.func
  misc/config-file.func
Labels: update script, bugfix, core

#6422 Refactor: Ombi
  ct/ombi.sh
  frontend/public/json/ombi.json
  install/ombi-install.sh
Labels: update script, json, refactor

#6423 Refactor: Opengist
  ct/opengist.sh
  frontend/public/json/opengist.json
  install/opengist-install.sh
Labels: update script, json, refactor

#6415 Refactor: Memos
  ct/memos.sh
  frontend/public/json/memos.json
  install/memos-install.sh
Labels: update script, json

#6399 Refactor: listmonk
  ct/listmonk.sh
  frontend/public/json/listmonk.json
  install/listmonk-install.sh
Labels: update script, json, refactor
