Repository community-scripts/ProxmoxVE, pull requests merged in 2025-04, with the labels that each got.

#3554 switch arr lxc's (lidarr,-prowlarr,-radarr,-readarr,-whisparr) to curl -fsSL
  ct/sonarr.sh
  ct/threadfin.sh
  install/lidarr-install.sh
  install/prowlarr-install.sh
  install/radarr-install.sh
  install/readarr-install.sh
  install/sonarr-install.sh
  install/threadfin-install.sh
  install/whisparr-install.sh
Labels: update script, bugfix

#3559 CheckMK: Increase Disk size
  ct/checkmk.sh
Labels: update script, bugfix

#3567 Refactor ScriptItem and Buttons components to enhance layout and integrate dropdown for links. Update InterFaces component for improved styling and structure.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/app/scripts/_components/ResourceDisplay.tsx
  frontend/src/app/scripts/_components/ScriptItem.tsx
  frontend/src/app/scripts/_components/ScriptItems/Alerts.tsx
  frontend/src/app/scripts/_components/ScriptItems/Buttons.tsx
  frontend/src/app/scripts/_components/ScriptItems/DefaultPassword.tsx
  frontend/src/app/scripts/_components/ScriptItems/DefaultSettings.tsx
  frontend/src/app/scripts/_components/ScriptItems/InterFaces.tsx
  frontend/src/app/scripts/_components/VersionBadge.tsx
  frontend/src/app/scripts/page.tsx
  frontend/src/components/icons/resource-icons.tsx
  frontend/src/components/query-provider.tsx
  frontend/src/hooks/useVersions.ts
  frontend/src/lib/utils/resource-utils.ts
Labels: website, feature, refactor

#3547 Alpine Prometheus
  ct/alpine-prometheus.sh
  frontend/public/json/prometheus.json
  install/alpine-prometheus-install.sh
Labels: website, new script, json

#3577 Fileflows: Fix update dependencies
  ct/fileflows.sh
  install/fileflows-install.sh
Labels: update script, bugfix

#3587 General fixes for several scripts
  ct/actualbudget.sh
  ct/emby.sh
  ct/snipeit.sh
  install/daemonsync-install.sh
  install/deconz-install.sh
  install/paperless-ngx-install.sh
Labels: update script, bugfix, refactor

#3589 Fileflows: Add ImageMagick dependecy
  install/fileflows-install.sh
Labels: update script, bugfix

#3593 Fix link in clean-lxcs.sh
  misc/clean-lxcs.sh
Labels: update script, bugfix

#3598 UI-Fix: verbose without useless space in header
  misc/build.func
Labels: maintenance, high risk, core

#3601 Photoprism: harmonize curl
  ct/photoprism.sh
  install/photoprism-install.sh
Labels: update script, bugfix

#3612 Authelia: fix incorrect rights for email.txt
  install/authelia-install.sh
Labels: update script, bugfix

#3604 CrowdSec: Update install URL and script refresh
  misc/crowdsec.sh
Labels: update script, bugfix, refactor

#3620 Fix missing favicon on website
  frontend/src/app/layout.tsx
Labels: website, bugfix

#3621 Update Footer.tsx to redirect to frontend page instead of home page
  frontend/src/components/Footer.tsx
Labels: website, bugfix

#3627 BookStack: Fix path to downloaded release file
  ct/bookstack.sh
Labels: update script, bugfix

#3624 GoMFT: Fix the node_modules deletion command
  ct/gomft.sh
Labels: update script, bugfix

#3625 *Arr: Move Arr apps to github release crawling and provide update functionality
  ct/lidarr.sh
  ct/prowlarr.sh
  ct/radarr.sh
  frontend/public/json/lidarr.json
  frontend/public/json/prowlarr.json
  frontend/public/json/radarr.json
  install/lidarr-install.sh
  install/prowlarr-install.sh
  install/radarr-install.sh
Labels: website, update script, feature, json, refactor

#3633 slskd: fix typo for config note
  frontend/public/json/slskd.json
Labels: website, json

#3640 Prowlarr: Fix Typo in URL (update_function)
  ct/prowlarr.sh
Labels: update script, bugfix

#3657 Caddy: add git for xcaddy
  install/caddy-install.sh
Labels: update script, feature

#3669 Pelican Panel: Bump php to 8.4
  ct/pelican-panel.sh
  install/pelican-panel-install.sh
Labels: update script, bugfix

#3700 Pelican-Panel: Fix PHP 8.4 Repository
  install/pelican-panel-install.sh
Labels: update script, bugfix

#3703 Actual: Add git dependency & change yarn commands
  ct/actualbudget.sh
  install/actualbudget-install.sh
Labels: update script, bugfix

#3709 Implement FAQ component and integrate it into the main page
  frontend/package-lock.json
  frontend/src/app/page.tsx
  frontend/src/app/scripts/_components/ScriptAccordion.tsx
  frontend/src/components/FAQ.tsx
  frontend/src/components/Footer.tsx
  frontend/src/config/faqConfig.tsx
Labels: website, feature, bugfix

#3713 Actual: Increase RAM and add heap-space var for nodejs
  ct/actualbudget.sh
  frontend/public/json/actualbudget.json
  install/actualbudget-install.sh
Labels: website, update script, json

#3716 Zitadel: Fix release tarball crawling
  ct/zitadel.sh
  install/zitadel-install.sh
Labels: update script, bugfix

#3720 Refactor: Zabbix, get always latest version
  ct/zabbix.sh
  install/zabbix-install.sh
Labels: update script, refactor

#3724 Kimai: bump php to 8.4
  ct/kimai.sh
  install/kimai-install.sh
Labels: update script, feature

#3729 Changed the category of Channels DVR and NextPVR
  frontend/public/json/channels.json
  frontend/public/json/nextpvr.json
Labels: website, json

#3701 Alpine-MariaDB: Fix Install Service startup
  install/alpine-mariadb-install.sh
Labels: update script, bugfix

#3739 Alpine-MariaDB: better handling of adminer installation
  install/alpine-mariadb-install.sh
Labels: update script, feature

#3738 Paperless-GPT: Add logging to service file
  install/paperless-gpt-install.sh
Labels: update script, feature

#3741 TriliumNext: fix dump-db
  ct/trilium.sh
Labels: update script, bugfix

#3730 Actual: Reduce RAM to 4GB and old space to 3072MB
  ct/actualbudget.sh
  frontend/public/json/actualbudget.json
  install/actualbudget-install.sh
Labels: website, update script, json

#3749 Meilisearch: Fix Typo
  frontend/public/json/meilisearch.json
Labels: website, json

#3762 Tandoor: Add xmlsec as dependency
  ct/tandoor.sh
  install/tandoor-install.sh
Labels: update script, bugfix

#3769 core: a few path corrections
  tools/pve/clean-lxcs.sh
  tools/pve/cron-update-lxcs.sh
  tools/pve/frigate-support.sh
  tools/pve/hw-acceleration.sh
Labels: bugfix

#3771 core: Removal of OS/Version Selection from Advanced Settings
  ct/debian.sh
  ct/ubuntu.sh
  misc/build.func
Labels: maintenance, breaking change, core

#3773 HomeAssistantOS: allow Proxmox version 8.4
  vm/haos-vm.sh
Labels: update script, bugfix

#3779 harmonize pve versions check & vm vars
  misc/build.func
  tools/addon/netdata.sh
  tools/pve/add-lxc-iptag.sh
  tools/pve/hw-acceleration.sh
  tools/pve/post-pve-install.sh
  vm/archlinux-vm.sh
  vm/debian-vm.sh
  vm/docker-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/opnsense-vm.sh
  vm/owncloud-vm.sh
  vm/ubuntu2204-vm.sh
  vm/ubuntu2404-vm.sh
  vm/ubuntu2410-vm.sh
Labels: maintenance, high risk, update script, core, refactor

#3785 Paperless-NGX: remove gunicorn, use python3 for webserver
  install/paperless-ngx-install.sh
Labels: update script, bugfix

#3783 add Linkwarden frontend updateable tag
  frontend/public/json/linkwarden.json
Labels: invalid, website, json

#3790 Paperless-NGX: Extend Granian Service Env
  install/paperless-ngx-install.sh
Labels: update script, bugfix

#3801 Remove Actualbudget
  ct/actualbudget.sh
  ct/headers/actualbudget
  frontend/public/json/actualbudget.json
  install/actualbudget-install.sh
Labels: website, delete script

#3808 New Feature: Config File
  misc/build.func
Labels: maintenance, high risk, core

#3820 2FAuth: Fix php dependencies
  install/2fauth-install.sh
Labels: update script, bugfix

#3828 slskd: fix missing -o for curl
  ct/slskd.sh
Labels: update script, bugfix

#3830 Radicale: move to misc category
  frontend/public/json/radicale.json
Labels: website, json

#3838 SQLServer: fix some typos in notes
  frontend/public/json/sqlserver2022.json
Labels: website, json

#3852 Add "Not Updateable" tooltip to scripts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/scripts/_components/ScriptItems/Tooltips.tsx
  frontend/src/components/ui/tooltip.tsx
Labels: website, feature

#3825 Paymenter: bump php to 8.3
  ct/paymenter.sh
  frontend/public/json/paymenter.json
  install/paymenter-install.sh
Labels: website, update script, json

#3875 Alpine-AdGuardHome
  ct/alpine-adguard.sh
  frontend/public/json/adguard.json
  install/alpine-adguard-install.sh
Labels: website, new script, json

#3871 Neo4j: Add Java dependency
  ct/neo4j.sh
  install/neo4j-install.sh
Labels: update script, bugfix

#3878 Refactor Cockpit update_script part
  ct/cockpit.sh
Labels: update script, refactor

#3885 Omada: Increase RAM to 3GB and little improvements
  ct/omada.sh
  frontend/public/json/omada.json
  install/omada-install.sh
Labels: website, update script, json

#3892 SABnzbd: Fix update error caused by externaly managed message
  ct/sabnzbd.sh
Labels: update script, bugfix

#3895 Outline: Installation and update fixes
  ct/outline.sh
  install/outline-install.sh
Labels: update script, bugfix, refactor

#3902 shrink & minimalize report templates
  .github/DISCUSSION_TEMPLATE/request-script.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: maintenance, github

#3921 fix minor grammatical error in several scripts
  ct/create_lxc.sh
  tools/addon/all-templates.sh
  turnkey/turnkey.sh
  vm/archlinux-vm.sh
  vm/debian-vm.sh
  vm/docker-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/opnsense-vm.sh
  vm/owncloud-vm.sh
  vm/pimox-haos-vm.sh
  vm/ubuntu2204-vm.sh
  vm/ubuntu2404-vm.sh
  vm/ubuntu2410-vm.sh
Labels: maintenance, high risk, update script, core

#3922 GoMFT: Fix install and update process (final time)
  ct/gomft.sh
  install/gomft-install.sh
Labels: update script, bugfix

#3925 PeaNUT: Fix tar command
  ct/peanut.sh
  install/peanut-install.sh
Labels: update script, bugfix

#3929 VaultWarden: Update json with additonal information
  frontend/public/json/vaultwarden.json
Labels: website, json

#3935 Changedetection: Increase connection timeout for older systems
  install/changedetection-install.sh
Labels: update script, bugfix

#3953 seelf: Add missing gpg dependency
  install/seelf-install.sh
Labels: update script, bugfix

#3952 Tailscale: Clarify tailscale script instruction on website
  frontend/public/json/add-tailscale-lxc.json
Labels: website, json

#3531 LXC Iptag
  misc/add-iptag.sh
Labels: new script

#3969 qBittorrent: Update web page
  frontend/public/json/qbittorrent.json
Labels: website, json

#3974 wger: Fix a bug in update procedure and general code maintenance
  ct/wger.sh
  install/wger-install.sh
Labels: update script, bugfix

#3978 Fix Turnkey Source Link in Button Component
  frontend/src/app/scripts/_components/ScriptItems/Buttons.tsx
Labels: website, bugfix

#3981 Add workflow to close ttek Repo relatate issues
  .github/workflows/close-ttek-issues.yaml
Labels: maintenance, github

#3992 karakeep: use nightly channel for yt-dlp
  ct/karakeep.sh
  install/karakeep-install.sh
Labels: update script, bugfix

#3999 Fix Workflow to close discussions
  .github/workflows/close-discussion.yml
Labels: maintenance, github

#3998 Add ability to enable corosync when HA gets disabled.
  tools/pve/post-pve-install.sh
Labels: feature

#3997 Zipline: Add new ENV Variable and Change Update
  ct/zipline.sh
  install/zipline-install.sh
Labels: update script, bugfix

#4012 SLSKD: always check for soularr update
  ct/slskd.sh
Labels: update script, bugfix

#4010 Element Synapse: Add Synapse-Admin web UI to manage Matrix
  ct/elementsynapse.sh
  frontend/public/json/elementsynapse.json
  install/elementsynapse-install.sh
Labels: website, update script, json

#4019 Remove Whoogle
  ct/headers/whoogle
  ct/whoogle.sh
  frontend/public/json/whoogle.json
  install/whoogle-install.sh
  misc/images/whoogle.png
Labels: website, delete script

#4005 Feat: Add config path to website
  frontend/public/json/podman-homeassistant.json
  frontend/public/json/watchyourlan.json
  frontend/src/app/json-editor/_schemas/schemas.ts
  frontend/src/app/json-editor/page.tsx
  frontend/src/app/scripts/_components/ScriptItem.tsx
  frontend/src/app/scripts/_components/ScriptItems/ConfigFile.tsx
  frontend/src/components/ui/config-copy-button.tsx
  frontend/src/lib/types.ts
Labels: website, feature, json

#4020 Cleanup misc folder
  frontend/public/json/daemonsync.json
  frontend/public/json/openobserve.json
  misc/images/daemon-sync.png
  misc/images/filebrowser.png
  misc/images/haos.png
  misc/images/openobsecure.png
Labels: invalid, website, delete script, json

#4026 Pi-Hole: Fix Unbound update
  ct/pihole.sh
Labels: update script, feature

#4028 Fix JSON for Nextpvr
  frontend/public/json/nextpvr.json
Labels: invalid, website, json

#4029 Jellyfin: Mark as updateable
  frontend/public/json/jellyfin.json
Labels: website, json

#4041 Element Synapse: Fix Admin UI install and update procedure
  ct/elementsynapse.sh
  install/elementsynapse-install.sh
Labels: update script, bugfix

#4050 Element Synapse: Fix update for older versions
  ct/elementsynapse.sh
Labels: update script, bugfix

#4055 Filebrowser: Add Category Files & Donwloads
  frontend/public/json/filebrowser.json
Labels: website, json

#4059 Only show update source when app is marked updateable
  frontend/src/app/scripts/_components/ScriptItems/Buttons.tsx
Labels: website, bugfix

#4066 Element Synapse: Fix install script cd command error
  install/elementsynapse-install.sh
Labels: update script, bugfix

#4074 add default configuration file location for Caddy LXC
  frontend/public/json/caddy.json
Labels: website, json

#4079 Re-Add DeamonSync Package
  tools/addon/daemonsync_2.2.0.0059_amd64.deb
Labels: bugfix

#4102 clean-lxc.sh: cancel/no whiptail support
  tools/pve/clean-lxcs.sh
Labels: bugfix

#4101 fstrim: cancel/no whiptail support
  tools/pve/fstrim.sh
Labels: bugfix

#4103 core: remove unneeded logging
  misc/build.func
Labels: maintenance, high risk, core, refactor

#4108 Website: Fix frontend path in footer
  frontend/src/components/Footer.tsx
Labels: website

#4106 GoMFT: Move configuration info into config_path
  frontend/public/json/gomft.json
Labels: website, json

#4086 Install rsync in ct/commafeed.sh
  ct/commafeed.sh
Labels: update script, bugfix

#4118 CheckMK added filter to not install beta versions
  ct/checkmk.sh
  install/checkmk-install.sh
Labels: update script, bugfix

#4090 Feat: Random Script picker for Website
  frontend/src/components/CommandMenu.tsx
  package-lock.json
Labels: website, feature

#4120 Refactor: Navidrome
  ct/navidrome.sh
  install/navidrome-install.sh
Labels: update script, refactor

#4123 SECURITY.md: add pve 8.4 as supported
  SECURITY.md
Labels: documentation, maintenance

#4124 Umlautadaptarr Service File
  install/umlautadaptarr-install.sh
Labels: update script, bugfix

#4133 core: persist /usr/local/bin via profile.d helper
  misc/tools.func
Labels: maintenance, update script, core

#4127 Refactor: sabnzbd
  ct/sabnzbd.sh
  frontend/public/json/sabnzbd.json
  install/sabnzbd-install.sh
Labels: website, update script, json, refactor

#4147 Refactor: Ollama & Adding to Website
  ct/ollama.sh
  frontend/public/json/ollama.json
  install/ollama-install.sh
Labels: website, update script

#4148 Refactor: Matterbridge
  ct/matterbridge.sh
  frontend/public/json/matterbridge.json
  install/matterbridge-install.sh
Labels: website, update script, json

#4154 mark Caddy as updateable
  frontend/public/json/caddy.json
Labels: website, json
