Repository community-scripts/ProxmoxVE, pull requests merged in 2025-03, with the labels that each got.

#2752 [gh]: Fix Release Creation if Changelog.md to long
  .github/workflows/github-release.yml
Labels: maintenance, bugfix, github

#2756 Vikunja: Fixed update process
  ct/vikunja.sh
Labels: invalid, update script

#2757 homarr: double restart to fix homarr migration
  ct/homarr.sh
Labels: update script, bugfix

#2759 Firefly III: FIx Ownership for OAuth Key
  install/firefly-install.sh
Labels: update script, bugfix

#2768 Breaking: Remove Update Function for Actual Budget until it fixed
  ct/actualbudget.sh
Labels: update script, breaking change

#2770 ActualBudget: New Installation Script with new Repo
  install/actualbudget-install.sh
Labels: update script, feature

#2774 Fix gpg Repo for nzbget
  install/nzbget-install.sh
Labels: update script, bugfix

#2787 Linkwarden: Fix & Update Monolith-Installation
  ct/linkwarden.sh
  install/linkwarden-install.sh
  json/linkwarden.json
Labels: website, update script, bugfix, json

#2785 Feature Template Path for Mountings
  ct/create_lxc.sh
Labels: maintenance, high risk, update script, feature, core

#2779 Habitica
  ct/habitica.sh
  install/habitica-install.sh
  json/habitica.json
Labels: website, new script

#2802 Update zigbee2mqtt.json - make sure link is clickable
  json/zigbee2mqtt.json
Labels: website, bugfix, json

#2805 Zigbee2Mqtt Use fixed pnpm Version 10.4.1
  ct/zigbee2mqtt.sh
Labels: update script, bugfix

#2812 fix(prometheus-paperless-ngx-exporter): Fix wrong Interface Port
  json/prometheus-paperless-ngx-exporter.json
Labels: website, bugfix, json

#2813 Nginx: Fix $STD for tar
  ct/nginxproxymanager.sh
Labels: update script, bugfix

#2801 Pterodactyl Panel
  ct/pterodactyl-panel.sh
  install/pterodactyl-panel-install.sh
  json/pterodactyl-panel.json
Labels: website, new script

#2800 Pterodactyl Wings
  ct/pterodactyl-wings.sh
  install/pterodactyl-wings-install.sh
  json/pterodactyl-wings.json
Labels: website, new script

#2824 Json file update
  json/authelia.json
  json/baikal.json
  json/barcode-buddy.json
  json/beszel.json
  json/cosmos.json
  json/crafty-controller.json
  json/elementsynapse.json
  json/freshrss.json
  json/ghost.json
  json/glpi.json
  json/koillection.json
  json/paymenter.json
  json/pelican-panel.json
  json/pelican-wings.json
  json/pocketid.json
  json/pterodactyl-wings.json
  json/radicale.json
  json/urbackupserver.json
  json/wordpress.json
Labels: website, bugfix, json

#2823 Website: Add Mikrotik to Network too, OPNSense & OpenWRT to OS
  json/mikrotik-routeros.json
  json/openwrt.json
  json/opnsense-vm.json
Labels: website, feature, json

#2818 Better handling of create release
  .github/workflows/github-release.yml
Labels: maintenance, bugfix, github

#2806 Reveal.js
  ct/revealjs.sh
  install/revealjs-install.sh
  json/revealjs.json
Labels: website, new script

#2853 Fix NextcloudPi-Installation
  install/nextcloudpi-install.sh
Labels: update script, bugfix

#2864 Heimdall Dashboard: Updated the composer call
  ct/heimdall-dashboard.sh
Labels: invalid, update script, bugfix

#2862 Kimai: Better Handling of Updates (backup var / env / yaml)
  ct/kimai.sh
Labels: update script, bugfix

#2875 Fix Tag "community-scripts" for ArchLinux / OPNSense
  vm/archlinux-vm.sh
  vm/opnsense-vm.sh
Labels: update script, bugfix

#2876 Homarr: Optional Reboot after update
  ct/homarr.sh
Labels: update script, bugfix

#2896 Wastebin: fix unzip command
  ct/wastebin.sh
Labels: invalid

#2904 Update Apache Tika icon to SVG
  json/apache-tika.json
Labels: website, feature, json

#2905 Update Prometheus Alertmanager Icon
  json/prometheus-alertmanager.json
Labels: website, json

#2922 fix jupyternotebook slug
  json/jupyternotebook.json
Labels: website, bugfix, json

#2924 JupyterNotebook: Fix APP Variable
  ct/jupyternotebook.sh
Labels: update script, bugfix

#2915 Beszel: restarting service after update
  ct/beszel.sh
Labels: update script, feature

#2907 ActualBudget: Update Script with new Repo
  ct/actualbudget.sh
Labels: update script, breaking change

#2929 Improve Trilium Description and Name to TriliumNext
  json/trilium.json
Labels: website, json

#2930 Improve Nextcloud(pi) docu and Name to NextcloudPi
  json/nextcloudpi.json
Labels: website, json

#2942 Update slug to lowercase in pf2etools.json
  json/pf2etools.json
Labels: website, bugfix, json

#2950 Fix wikijs update issue while backing up data
  ct/wikijs.sh
Labels: update script, bugfix

#2953 Pi-hole interface port in documentation
  json/pihole.json
Labels: website, json

#2934 Improve Release-Action (awk function)
  .github/workflows/github-release.yml
Labels: maintenance, bugfix, github

#2948 Open WebUI: reset code base before pulling update
  ct/openwebui.sh
Labels: invalid, update script, bugfix

#2964 pihole: fix path when accessing pihole using `pct enter`
  ct/pihole.sh
Labels: update script, bugfix

#2958 Hoarder: v0.23.0 dependency update
  ct/hoarder.sh
  install/hoarder-install.sh
Labels: update script, feature, bugfix

#2968 Update autolabeler.yml: Set Labels correctly
  .github/workflows/autolabeler.yml
Labels: maintenance, bugfix, github

#2965 Paperless-GPT
  ct/paperless-gpt.sh
  install/paperless-gpt-install.sh
  json/paperless-gpt.json
Labels: website, new script

#2971 FIX autolabeler.yml
  .github/workflows/autolabeler.yml
Labels: invalid

#2963 Rework SnipeIT: Tarball & Tempfile
  ct/snipeit.sh
  install/snipeit-install.sh
Labels: update script, bugfix

#2977 Paperless-GPT: fix typo preventing install to run
  ct/paperless-gpt.sh
Labels: invalid, update script

#2975 Add warnings about externaly sourced scripts
  json/casaos.json
  json/channels.json
  json/glances.json
  json/homeassistant.json
  json/iobroker.json
  json/mattermost.json
  json/nextcloudpi.json
  json/nginxproxymanager.json
  json/pialert.json
  json/pihole.json
  json/plex.json
  json/podman-homeassistant.json
  json/runtipi.json
  json/technitiumdns.json
  json/yunohost.json
Labels: website

#2979 Remove NVM dependency from scripts and fix GOlang dependency crawling
  install/cronicle-install.sh
  install/seelf-install.sh
Labels: invalid, update script

#2983 Additions and amends to the CONTIRBUTOR docs
  .github/CONTRIBUTOR_AND_GUIDES/CONTRIBUTING.md
  .github/CONTRIBUTOR_AND_GUIDES/ct/AppName.md
  .github/CONTRIBUTOR_AND_GUIDES/install/AppName-install.md
Labels: maintenance, github

#2987 Seafile
  ct/seafile.sh
  install/seafile-install.sh
  json/seafile.json
Labels: website, new script

#2996 Teddycloud: fix update function
  ct/teddycloud.sh
Labels: update script, bugfix

#2991 Jellyseer not labeled as updateable even though update function exists
  json/jellyseerr.json
Labels: website, update script, json

#2998 Fix Website - Show correct wget path for alpine
  json/alpine-it-tools.json
  json/alpine.json
Labels: website, json

#3000 Plant-it
  ct/plant-it.sh
  install/plant-it-install.sh
  json/plant-it.json
Labels: website, new script

#3004 Cleanup Old Project Files (figlet, app-header, images)
  misc/.app-headers
  misc/figlet.tar.xz
  misc/images/2025approved.png
  misc/images/heimdall.png
  misc/images/nocodb.png
  misc/images/photoprism.png
  misc/images/pimox.png
Labels: delete script

#3009 SnipeIT: Harmonize composer install to Project-Dockerfile
  install/snipeit-install.sh
Labels: update script, bugfix

#3012 Headscale: Re-enable Service after Update
  ct/headscale.sh
Labels: update script, bugfix

#2997 Feature: Filebrowser: support now alpine
  json/filebrowser.json
  misc/filebrowser.sh
Labels: website, update script, feature, json

#2869 New Script: Fluid Calendar
  ct/fluid-calendar.sh
  install/fluid-calendar-install.sh
  json/fluid-calendar.json
Labels: website, new script

#3036 Update Vaultwarden Source
  ct/vaultwarden.sh
  install/vaultwarden-install.sh
  json/vaultwarden.json
Labels: website, update script, json

#3048 Website: Fix Alpine "undefined" Link
  json/alpine.json
Labels: website, json

#3051 NPMplus
  ct/npmplus.sh
  install/npmplus-install.sh
  json/npmplus.json
Labels: website, new script

#3053 Update Fluid Calendar for v1.2.0
  ct/fluid-calendar.sh
  install/fluid-calendar-install.sh
Labels: update script, breaking change, bugfix

#3057 alpine-Install (core) add timezone (tz) check
  misc/alpine-install.func
Labels: maintenance, update script, core

#3064 OpenWebUI check if there are stashed changes before poping
  ct/openwebui.sh
Labels: update script, bugfix

#3046 Seafile - Minor bug fix: domain.sh script fix
  install/seafile-install.sh
  json/seafile.json
Labels: website, update script, json

#3072 Memos: Increase RAM Usage and max space
  ct/memos.sh
  install/memos-install.sh
  json/memos.json
Labels: website, update script

#3084 Update openwrt.sh
  vm/openwrt.sh
Labels: invalid

#3085 NPM: Add info about docker use.
  json/npmplus.json
Labels: website, json

#3092 Homepage: Bugfix for v1.0.0
  ct/homepage.sh
  install/homepage-install.sh
  json/homepage.json
Labels: update script, breaking change

#3105 Fix hardcoded port in Debian service file
  misc/filebrowser.sh
Labels: update script, bugfix

#3098 Prometheus PVE Exporter: Rightsizing RAM and Disk
  ct/prometheus-pve-exporter.sh
  json/prometheus-pve-exporter.json
Labels: website, update script, json

#3111 Paperless-NGS: Add additional information to website on how to install OCR languages
  json/paperless-ngx.json
Labels: website, update script, json

#3115 Typo Enviroment > Environment
  install/nginxproxymanager-install.sh
Labels: update script

#3121 wger: Fix build.func path
  ct/wger.sh
Labels: update script, bugfix

#3125 Jellyseerr: Fix dependencies
  install/jellyseerr-install.sh
Labels: update script, bugfix

#3110 Website: Fix alpine-it-tools "undefined" Link
  json/alpine-it-tools.json
Labels: website, json

#3132 ByteStash: Add option for multiple accounts and generate JWT secret
  install/bytestash-install.sh
Labels: enhancement, update script

#3136 Kimai: Fix Permission Issue on new Timerecords
  ct/kimai.sh
  install/kimai-install.sh
Labels: update script, bugfix

#3141 InfluxDB: Add Ports as Info / Script-End
  ct/influxdb.sh
  json/influxdb.json
Labels: website, update script, json

#3140 Tandoor: Switch Repo to new Link
  install/tandoor-install.sh
Labels: update script, bugfix

#3143 Fixed wrong PHP values to match default part-db size (100M)
  install/part-db-install.sh
Labels: update script, bugfix

#3150 qBittorrent: Accept legal notice in config file
  install/qbittorrent-install.sh
Labels: update script, bugfix

#3152 TriliumNext: Fix release file name/path, preventing install and update
  ct/trilium.sh
  install/trilium-install.sh
Labels: update script

#3155 Paperless-ngx: Fix example on website
  json/paperless-ngx.json
Labels: website, update script, json

#3160 TriliumNotes: Fix release handling
  ct/trilium.sh
  install/trilium-install.sh
Labels: update script, bugfix

#3157 GoMFT
  ct/gomft.sh
  install/gomft-install.sh
  json/gomft.json
Labels: website, new script

#3187 Change json path CONTRIBUTING.md
  .github/CONTRIBUTOR_AND_GUIDES/CONTRIBUTING.md
Labels: maintenance, github

#3185 Update Workflow to Close Discussion
  .github/workflows/close-discussion.yml
Labels: maintenance, github

#3188 GoMFT: Update Logo
  frontend/public/json/gomft.json
Labels: website, json

#3192 Add worflow to crawl APP verisons
  .github/workflows/crawl-versions.yaml
  frontend/public/json/versions.json
  frontend/src/__tests__/public/validate-json.test.ts
  frontend/src/app/api/categories/route.ts
  frontend/tsconfig.json
Labels: website, maintenance, github

#3197 Fix wrong repo in WF
  .github/workflows/crawl-versions.yaml
Labels: invalid

#3199 Fix frontend
  frontend/src/app/api/categories/route.ts
Labels: invalid

#3200 Update pr template and WF
  .github/autolabeler-config.json
  .github/changelog-pr-config.json
  .github/pull_request_template.md
  .github/workflows/autolabeler.yml
  .github/workflows/changelog-pr.yml
Labels: maintenance, github

#3206 Fix changelog wf
  .github/workflows/changelog-pr.yml
Labels: invalid

#3205 CryptPad
  cryptpad-install.sh
  cryptpad.json
  cryptpad.sh
Labels: new script

#3207 Tandoor: Extend needed dependencies (Read for Update-Functionality)
  install/tandoor-install.sh
Labels: update script, breaking change

#3208 Shorten PR Template for ProxmoxVE (Remove some VED Things)
  .github/pull_request_template.md
Labels: invalid, maintenance, github

#3209 Seafile: lowercase slug for Install/Update-Source
  frontend/public/json/seafile.json
Labels: website, json

#3213 Fix openwebui update script when backup directory already exists
  ct/openwebui.sh
Labels: update script, bugfix

#3212 Update changelog-pr.yml
  .github/workflows/changelog-pr.yml
Labels: invalid

#3216 Show Version Information on Frontend
  frontend/src/app/api/versions/route.ts
  frontend/src/app/scripts/_components/ScriptItem.tsx
  frontend/src/lib/data.ts
  frontend/src/lib/types.ts
Labels: website, feature

#3215 Debian VM: Update webpage with login info
  frontend/public/json/debian-vm.json
Labels: website, json

#3219 Add label to Workflow PR
  .github/workflows/crawl-versions.yaml
Labels: invalid

#3222 Website: Lowercase Zitadel-Slug
  frontend/public/json/zitadel.json
Labels: website, json

#3225 VictoriaMetrics: Fix Wrong Slug
  frontend/public/json/victoriametrics.json
Labels: website, json

#3210 CrowdSec: Add debian only warning to website
  frontend/public/json/crowdsec.json
Labels: website, json

#3227 Heimdall Dashboard: Fix missing logo on website
  frontend/public/json/heimdall-dashboard.json
Labels: website, json

#3233 Update Pimox Logo
  frontend/public/json/pimox-haos-vm.json
Labels: website, json

#3232 Fix wikijs
  ct/wikijs.sh
  install/wikijs-install.sh
Labels: update script, bugfix

#3235 Update crawl-versions.yaml
  .github/workflows/crawl-versions.yaml
Labels: invalid, maintenance, github

#3231 Add Latest Change Date to Frontend
  .github/workflows/crawl-versions.yaml
  frontend/src/app/api/versions/route.ts
  frontend/src/app/scripts/_components/ScriptItem.tsx
  frontend/src/lib/types.ts
Labels: website, maintenance, github

#3240 Fronted update
  frontend/src/app/api/versions/route.ts
Labels: invalid

#3242 Move cryptpad files to right folders
  ct/cryptpad.sh
  frontend/public/json/cryptpad.json
  install/cryptpad-install.sh
Labels: website, bugfix

#3245 Update omada download url
  ct/omada.sh
  install/omada-install.sh
Labels: update script, bugfix

#3250 Fluid-Calendar: Remove unneeded $STD in update
  ct/fluid-calendar.sh
Labels: update script, bugfix

#3256 Snipe-IT: Remove composer update & add no interaction for install
  ct/snipeit.sh
  install/snipeit-install.sh
Labels: update script, bugfix

#3258 License url VED to VE
  ct/npmplus.sh
  ct/paperless-gpt.sh
  install/paperless-gpt-install.sh
Labels: update script

#3276 Netdata: Update to newer deb File
  misc/netdata.sh
Labels: update script, feature

#3278 [core] add gitignore to prevent big pulls
  .gitignore
Labels: feature, github

#3293 Proxmox, rather than Promox
  frontend/public/json/proxmox-mail-gateway.json
Labels: website, json

#3295 Threadfin: add port for website
  frontend/public/json/threadfin.json
Labels: website, json

#3296 Clarify MTU in advanced Settings.
  misc/build.func
Labels: maintenance, high risk, core

#3304 Update audiobookshelf.json
  frontend/public/json/audiobookshelf.json
Labels: website, json

#3302 Update repo tree to fix .editorconfig beign ignored.
  .editorconfig
Labels: refactor

#3303 GoMFT: Don't rely on binaries from github
  ct/gomft.sh
  install/gomft-install.sh
Labels: update script, bugfix

#3313 GoMFT: Fix build dependencies
  ct/gomft.sh
  install/gomft-install.sh
Labels: update script, bugfix, refactor

#3315 MySQL: Correctly add repo to mysql.list
  install/mysql-install.sh
Labels: update script, bugfix

#3318 Omada zulu 8 to 21
  ct/omada.sh
  install/omada-install.sh
Labels: update script, bugfix

#3319 Omada jdk to jre
  ct/omada.sh
  install/omada-install.sh
Labels: update script

#3323 Cronicle: add missing gnupg package
  install/cronicle-install.sh
Labels: update script, bugfix

#3333 Update nextcloud-vm.sh to 18.1 ISO
  vm/nextcloud-vm.sh
Labels: update script, feature

#3341 revealjs: Fix update process
  ct/revealjs.sh
Labels: update script, bugfix

#3358 GoMFT: Check if build-essential is present before updating, if not then install it
  ct/gomft.sh
Labels: update script, bugfix

#3371 Refactor Changelog Workflow
  .github/workflows/changelog-pr.yml
Labels: maintenance, github

#3366 [core] install core deps (debian / ubuntu)
  misc/install.func
Labels: maintenance, high risk, feature, core

#3372 Fix WF
  .github/workflows/changelog-pr.yml
Labels: invalid, maintenance, github

#3367 Extension/New Script: Redis Alpine Installation
  ct/alpine-redis.sh
  frontend/public/json/redis.json
  install/alpine-redis-install.sh
Labels: website, new script, json

#3377 Repair Changelog
  .github/workflows/changelog-pr.yml
Labels: invalid, maintenance, github

#3386 Wazuh small issues fixed
  ct/wazuh.sh
  frontend/public/json/wazuh.json
  install/wazuh-install.sh
Labels: invalid, website, update script, json

#3387 Fix Changelog Workflow
  .github/workflows/changelog-pr.yml
Labels: invalid, maintenance, github

#3389 Update siteConfig.tsx to use new analytics code
  frontend/src/config/siteConfig.tsx
Labels: website

#3396 [core] extend hardware transcoding for fileflows #3392
  misc/build.func
Labels: maintenance, high risk, core

#3397 Extend HOME Env for Kubo
  install/kubo-install.sh
Labels: update script, bugfix

#3405 qBittorrent: Switch to static builds for faster updating/upgrading
  ct/qbittorrent.sh
  install/qbittorrent-install.sh
Labels: update script, refactor

#3417 fluid-calendar: Fix failed build during updates
  ct/fluid-calendar.sh
Labels: update script, bugfix

#3420 Remove coredeps in CONTRIBUTOR_AND_GUIDES
  .github/CONTRIBUTOR_AND_GUIDES/install/AppName-install.md
  .github/CONTRIBUTOR_AND_GUIDES/install/AppName-install.sh
  install/fileflows-install.sh
Labels: maintenance, update script, github

#3424 Alpine: Gitea
  ct/alpine-gitea.sh
  frontend/public/json/gitea.json
  install/alpine-gitea-install.sh
Labels: website, new script, json

#3427 FlowiseAI: Fix dependencies
  frontend/public/json/flowiseai.json
  install/flowiseai-install.sh
Labels: website, update script, json

#3436 [core]: Refactor Spinner/MSG Function (support now alpine / performance / handling)
  misc/build.func
Labels: maintenance, high risk, core
