Repository community-scripts/ProxmoxVE, pull requests merged in 2025-05, with the labels that each got.

#4162 Grafana: add config path & documentation
  frontend/public/json/grafana.json
Labels: website, json

#4167 homepage: Add build time var
  ct/homepage.sh
  install/homepage-install.sh
Labels: update script, feature

#4172 Readeck: Fix release crawling
  ct/readeck.sh
  install/readeck-install.sh
Labels: update script, bugfix, refactor

#4181 Habitica: correct config path
  frontend/public/json/habitica.json
Labels: website, json

#4179 NetBox: Fix typo in sed command, preventing install
  install/netbox-install.sh
Labels: update script, bugfix

#4183 Changed the random script button to be the same as all the other buttons
  frontend/src/components/CommandMenu.tsx
  frontend/src/components/ui/code-copy-button.tsx
Labels: website, bugfix, refactor

#4186 SFTPGo: Switch updatable to true on website
  frontend/public/json/sftpgo.json
Labels: website, json

#4197 Vaultwarden: Enable HTTPS by default
  frontend/public/json/vaultwarden.json
  install/alpine-vaultwarden-install.sh
  install/vaultwarden-install.sh
Labels: website, update script, json

#4199 Vaultwarden: Fix access URL
  ct/vaultwarden.sh
Labels: update script, bugfix

#4211 Code Server: Update misleading name, description and icon.
  frontend/public/json/code-server.json
  frontend/public/json/coder-code-server.json
  tools/addon/coder-code-server.sh
Labels: website

#4229 Apache Guacamole: Fix Version Grepping
  install/apache-guacamole-install.sh
Labels: update script, bugfix

#4232 Alpine-Vaultwarden: Fix sed and better cert generation
  install/alpine-vaultwarden-install.sh
Labels: update script, bugfix, refactor

#4231 Refactor: Komodo update logic
  ct/komodo.sh
Labels: update script, refactor

#4237 Update apache-guacamole-install.sh
  install/apache-guacamole-install.sh
Labels: invalid

#4236 Refactor: linkwarden
  ct/linkwarden.sh
  install/linkwarden-install.sh
Labels: refactor

#4234 New Script: Alpine-Komodo
  ct/alpine-komodo.sh
  frontend/public/json/komodo.json
  install/alpine-komodo-install.sh
Labels: website, new script, json

#4238 tools.func: better function handling + gs as new helper
  misc/tools.func
Labels: maintenance, update script, core

#4241 Docker-VM: Add Disk Size choice
  vm/docker-vm.sh
Labels: update script, feature

#4245 Docker VM: Fix variable doublequoting
  vm/docker-vm.sh
Labels: update script, bugfix

#4228 Re-Add: ActualBudget
  ct/actualbudget.sh
  frontend/public/json/actualbudget.json
  install/actualbudget-install.sh
Labels: website, new script

#4259 whiptail menu - cancel button now exists the advanced menu
  misc/build.func
Labels: maintenance, high risk, bugfix, core

#3987 SuwayomiServer: Bump Java to v21, code formating
  ct/suwayomiserver.sh
  install/suwayomiserver-install.sh
Labels: update script, bugfix, refactor

#4288 Alpine scripts: Set minimum disk space to 0.5GB
  ct/alpine-it-tools.sh
  ct/alpine.sh
  frontend/public/json/alpine-it-tools.json
  frontend/public/json/alpine.json
Labels: website, update script, json

#4292 Feature: get correct next VMID
  vm/archlinux-vm.sh
  vm/debian-vm.sh
  vm/docker-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/opnsense-vm.sh
  vm/owncloud-vm.sh
  vm/pimox-haos-vm.sh
  vm/ubuntu2204-vm.sh
  vm/ubuntu2404-vm.sh
  vm/ubuntu2410-vm.sh
Labels: update script, feature

#4314 Streamlink-webui: fix path check for update
  ct/streamlink-webui.sh
Labels: invalid, update script, bugfix

#4300 FAQ: Explanation "updatable"
  frontend/src/config/faqConfig.tsx
Labels: website

#4322 SearXNG: fix to resolve yaml dependency error
  install/searxng-install.sh
Labels: update script, bugfix

#4328 streamlink-webui: fix variable names in update script
  ct/streamlink-webui.sh
Labels: invalid, update script, bugfix

#4329 OpenWebUI: Upscale resources
  ct/openwebui.sh
  frontend/public/json/openwebui.json
Labels: invalid, website, update script, json

#4339 Add a Repo check to all Workflows
  .github/workflows/auto-update-app-headers.yml
  .github/workflows/autolabeler.yml
  .github/workflows/changelog-pr.yml
  .github/workflows/close-discussion.yml
  .github/workflows/close-ttek-issues.yaml
  .github/workflows/close_issue_in_dev.yaml
  .github/workflows/crawl-versions.yaml
  .github/workflows/create-docker-for-runner.yml
  .github/workflows/delete-json-branch.yml
  .github/workflows/frontend-cicd.yml
  .github/workflows/github-release.yml
  .github/workflows/script-test.yml
  .github/workflows/script_format.yml
  .github/workflows/update-json-date.yml
  .github/workflows/validate-filenames.yml
Labels: maintenance, github

#4343 Auto-Merge Automatic PR
  .github/workflows/auto-update-app-headers.yml
  .github/workflows/changelog-pr.yml
  .github/workflows/crawl-versions.yaml
  .github/workflows/update-json-date.yml
Labels: maintenance, github

#4344 Feature: autologin for Alpine
  misc/alpine-install.func
Labels: maintenance, update script, feature, core

#4357 fix app/application var mapping
  misc/tools.func
Labels: invalid, maintenance, update script, core

#4351 fix: detect all bridge types, not just vmbr prefix
  misc/build.func
Labels: maintenance, high risk, core

#4362 Revert "fix: detect all bridge types, not just vmbr prefix"
  misc/build.func
Labels: invalid, maintenance, high risk, core

#4364 Authentik: change install to UV & increase resources to 10GB RAM
  ct/authentik.sh
  frontend/public/json/authentik.json
  install/authentik-install.sh
Labels: website, update script, bugfix, json

#4363 HomeAssistant-Core: update script for 2025.5+
  ct/homeassistant-core.sh
  install/homeassistant-core-install.sh
Labels: update script, feature

#4365 Jellyseerr: better handling of node and pnpm
  ct/jellyseerr.sh
  install/jellyseerr-install.sh
Labels: update script, bugfix

#4373 bazarr: Fix verbose mode
  install/bazarr-install.sh
Labels: invalid, update script, bugfix

#4371 HomeAssistant Container: Portainer is on https port
  ct/homeassistant.sh
Labels: invalid, update script, bugfix

#4382 (fix) Documenso: fix build failures
  ct/documenso.sh
  install/documenso-install.sh
Labels: update script, breaking change, bugfix

#4391 Zammad: Enable ElasticSearch service
  install/zammad-install.sh
Labels: update script, bugfix

#4406 Navidrome - Fix config path (use /etc/ instead of /var/lib)
  frontend/public/json/navidrome.json
Labels: website, json

#4296 Feature: LXC-Delete (pve helper): add "all items"
  tools/pve/lxc-delete.sh
Labels: update script, feature

#4414 Alpine: Use onliner for updates
  .github/workflows/scripts/app-test/pr-alpine-install.func
  ct/alpine-adguard.sh
  ct/alpine-docker.sh
  ct/alpine-gitea.sh
  ct/alpine-grafana.sh
  ct/alpine-mariadb.sh
  ct/alpine-node-red.sh
  ct/alpine-postgresql.sh
  ct/alpine-prometheus.sh
  ct/alpine-tinyauth.sh
  ct/alpine-vaultwarden.sh
  ct/alpine-wireguard.sh
  ct/alpine-zigbee2mqtt.sh
  ct/alpine.sh
  ct/npmplus.sh
  frontend/public/json/alpine.json
  misc/alpine-install.func
  tools/pve/update-lxcs-cron.sh
  tools/pve/update-lxcs.sh
Labels: website, maintenance, update script, github, json, core

#4412 Alpine-Traefik
  ct/alpine-traefik.sh
  frontend/public/json/traefik.json
  install/alpine-traefik-install.sh
Labels: website, new script, json

#4409 homarr: fetch versions dynamically from source repo
  ct/homarr.sh
  install/homarr-install.sh
Labels: update script, feature, bugfix

#4426 pingvin.json: fix typo
  frontend/public/json/pingvin.json
Labels: website, json

#4430 update some improvements from dev (tools.func)
  misc/tools.func
Labels: maintenance, update script, core

#4432 Pingvin Share: Added explanation on how to add/edit environment variables
  frontend/public/json/pingvin.json
Labels: website, json

#4438 openhab: use zulu17-jdk
  install/openhab-install.sh
Labels: update script, bugfix

#4413 fix: improve bridge detection in all network interface configuration files
  misc/build.func
Labels: maintenance, high risk, core

#4448 openhab. correct some typos
  install/openhab-install.sh
Labels: update script, refactor

#4434 Jellyfin Media Server: Update configuration path
  frontend/public/json/jellyfin.json
Labels: website, json

#4453 Gatus: Fix json
  frontend/public/json/gatus.json
Labels: invalid, website, json

#4456 Website: re-add documenso & some little bugfixes
  frontend/public/json/documenso.json
  install/documenso-install.sh
  misc/tools.func
Labels: website, maintenance, update script, core

#4461 Add Github app for auto PR merge
  .github/workflows/auto-update-app-headers.yml
  .github/workflows/changelog-pr.yml
  .github/workflows/update-json-date.yml
Labels: maintenance, github

#4457 Bookstack: fix copy of themes/uploads/storage
  ct/bookstack.sh
Labels: update script, bugfix

#4465 Alpine-Rclone: Fix location of passwords file
  ct/alpine-rclone.sh
  frontend/public/json/alpine-rclone.json
  install/alpine-rclone-install.sh
Labels: website, update script, bugfix, json

#4478 fix: fetch_release_and_deploy function
  misc/tools.func
Labels: maintenance, update script, core

#4481 quickfix: fix homarr folder
  ct/homarr.sh
Labels: invalid, update script, bugfix

#4485 Add make installation dependency to Actual Budget script
  install/actualbudget-install.sh
Labels: update script, bugfix

#4489 HomeAssistant-Core: add Deprecation-Warning for August 2025
  frontend/public/json/homeassistant-core.json
Labels: website, json

#4496 core: Add TAB3 formatting var to core
  misc/alpine-install.func
  misc/build.func
  misc/install.func
Labels: maintenance, high risk, update script, core

#4495 core: fix bridge detection for OVS
  misc/build.func
Labels: maintenance, high risk, core

#4513 go2rtc: Fix tags
  ct/go2rtc.sh
Labels: invalid, update script

#4518 Updates to contributor docs/guide
  .github/CONTRIBUTOR_AND_GUIDES/ct/AppName.md
  .github/CONTRIBUTOR_AND_GUIDES/ct/AppName.sh
  .github/CONTRIBUTOR_AND_GUIDES/install/AppName-install.md
  .github/CONTRIBUTOR_AND_GUIDES/install/AppName-install.sh
Labels: maintenance, github

#4522 [core] Fix Bridge detection in Advanced Mode
  misc/build.func
Labels: maintenance, high risk, core

#4523 [core] Enable SSH_KEY and SSH without password
  misc/build.func
Labels: maintenance, high risk, core

#4528 [core] Refactor Config File function
  misc/build.func
  misc/config-file.func
Labels: maintenance, core

#4537 build.func update
  misc/build.func
Labels: invalid

#4553 Alpine Transmission: Add a slight pause before stopping the service
  install/alpine-transmission-install.sh
Labels: invalid, update script, bugfix

#4562 tools.func - Add function to create self-signed certificates
  misc/tools.func
Labels: maintenance, update script, core

#4569 Homarr: fix the build
  ct/homarr.sh
  install/homarr-install.sh
Labels: update script, bugfix

#4570 Fix Dashy Config Path on Frontend
  frontend/public/json/dashy.json
Labels: website, json

#4577 quickfix homarr install
  install/homarr-install.sh
Labels: invalid, update script, bugfix

#4578 Quickfix homarr
  install/homarr-install.sh
Labels: invalid, update script, bugfix

#4583 increase ressources of Homarr (3 vCPU / 6GB RAM)
  ct/homarr.sh
  frontend/public/json/homarr.json
Labels: website, update script, json

#4590 RustDesk Server: Add WebUI
  ct/rustdeskserver.sh
  frontend/public/json/rustdeskserver.json
  install/rustdeskserver-install.sh
Labels: website, update script, json

#4549 Various unrelated fixes to kimai update script
  ct/kimai.sh
Labels: update script, bugfix

#4605 [tools.func]: Update fetch_and_deploy_gh_release function
  misc/tools.func
Labels: maintenance, update script, core

#4612 RustDesk Server: Fix update for older installs
  ct/rustdeskserver.sh
Labels: update script, bugfix

#4628 Alpine-Node-RED: Update Service File
  install/alpine-node-red-install.sh
Labels: update script, bugfix

#4635 Paperless-AI: Add RAG chat
  ct/paperless-ai.sh
  install/paperless-ai-install.sh
Labels: update script, feature, refactor

#4665 Commafeed: move to Documents category
  frontend/public/json/commafeed.json
Labels: website, json

#4668 Paperless-AI: Upscale the resources
  ct/paperless-ai.sh
  frontend/public/json/paperless-ai.json
Labels: invalid, website, update script, json

#4680 Update Icons to selfhst/icons (FreePBX & Configarr)
  frontend/public/json/configarr.json
  frontend/public/json/freepbx.json
Labels: website, json

#4682 Zammad: Update website link
  frontend/public/json/zammad.json
Labels: invalid, website, json

#4694 Cloudflare-DDNS: Fix path to executable in service file
  install/cloudflare-ddns-install.sh
Labels: invalid, update script, bugfix

#4696 Grafana: Update config paths
  frontend/public/json/grafana.json
Labels: invalid, website, json

#4701 Pterodactyl panel read typo
  install/pterodactyl-panel-install.sh
Labels: update script, refactor

#4742 lldap: fix update-check
  ct/lldap.sh
Labels: update script, bugfix

#4744 Big NodeJS Update: Use Helper Function on all Install-Scripts
  install/adventurelog-install.sh
  install/archivebox-install.sh
  install/bytestash-install.sh
  install/changedetection-install.sh
  install/cronicle-install.sh
  install/cross-seed-install.sh
  install/cryptpad-install.sh
  install/dashy-install.sh
  install/docmost-install.sh
  install/elementsynapse-install.sh
  install/excalidraw-install.sh
  install/flowiseai-install.sh
  install/frigate-install.sh
  install/ghost-install.sh
  install/gomft-install.sh
  install/grist-install.sh
  install/habitica-install.sh
  install/homepage-install.sh
  install/iobroker-install.sh
  install/karakeep-install.sh
  install/koillection-install.sh
  install/mafl-install.sh
  install/magicmirror-install.sh
  install/meilisearch-install.sh
  install/memos-install.sh
  install/meshcentral-install.sh
  install/metube-install.sh
  install/monica-install.sh
  install/myspeed-install.sh
  install/n8n-install.sh
  install/node-red-install.sh
  install/nodebb-install.sh
  install/openwebui-install.sh
  install/outline-install.sh
  install/overseerr-install.sh
  install/pairdrop-install.sh
  install/paperless-gpt-install.sh
  install/part-db-install.sh
  install/peanut-install.sh
  install/pf2etools-install.sh
  install/pingvin-install.sh
  install/ps5-mqtt-install.sh
  install/revealjs-install.sh
  install/seelf-install.sh
  install/shinobi-install.sh
  install/tandoor-install.sh
  install/tasmocompiler-install.sh
  install/the-lounge-install.sh
  install/tianji-install.sh
  install/umami-install.sh
  install/uptimekuma-install.sh
  install/watcharr-install.sh
  install/web-check-install.sh
  install/wger-install.sh
  install/wikijs-install.sh
  install/zigbee2mqtt-install.sh
  install/zipline-install.sh
  misc/tools.func
Labels: update script, feature, refactor

#4750 tools.func: little bugfixes | add rust install | add adminer install
  misc/tools.func
Labels: update script, core

#4753 merge MariaDB to tools.func Installer
  install/2fauth-install.sh
  install/apache-guacamole-install.sh
  install/bookstack-install.sh
  install/dolibarr-install.sh
  install/firefly-install.sh
  install/ghost-install.sh
  install/glpi-install.sh
  install/kimai-install.sh
  install/mariadb-install.sh
  install/monica-install.sh
  install/paymenter-install.sh
  install/pelican-panel-install.sh
  install/phpipam-install.sh
  install/plant-it-install.sh
  install/projectsend-install.sh
  install/pterodactyl-panel-install.sh
  install/shinobi-install.sh
  install/snipeit-install.sh
  install/wavelog-install.sh
  install/wordpress-install.sh
Labels: update script, refactor

#4756 Refactor: Linkwarden + OS Upgrade
  ct/linkwarden.sh
  frontend/public/json/linkwarden.json
  install/linkwarden-install.sh
  misc/tools.func
Labels: update script, breaking change, refactor

#4783 Alpine-Node-RED: add service to rc
  install/alpine-node-red-install.sh
Labels: update script, bugfix

#4796 Habitica: Use Node20
  install/habitica-install.sh
Labels: update script, bugfix

#4788 Umbrel-OS
  ct/umbrel.sh
  frontend/public/json/umbrel-os-vm.json
  install/umbrel-install.sh
  vm/umbrel-os-vm.sh
Labels: website, new script

#4810 Umbrel: Fix MachineType
  vm/umbrel-os-vm.sh
Labels: invalid, update script

#4809 pulse: correct url in note
  frontend/public/json/pulse.json
Labels: website, json

#4821 Docker-VM: set individual Hostname / Disk-Space formatting
  frontend/public/json/docker-vm.json
  vm/docker-vm.sh
Labels: website, update script, feature, json

#4828 Alpine Traefik: Fix Dashboard not beign accessible
  install/alpine-traefik-install.sh
Labels: update script, bugfix, refactor

#4831 Docmost: add jq before nodejs install
  install/docmost-install.sh
Labels: update script, bugfix

#4845 Update package dependencies in package.json and package-lock.json
  frontend/package-lock.json
  frontend/package.json
Labels: website, bugfix

#4869 Revert "Update package dependencies in package.json and package-lock.json (#4845)
  frontend/package-lock.json
  frontend/package.json
Labels: website, bugfix

#4868 Omada Controller: Fix libssl url
  install/omada-install.sh
Labels: update script, bugfix

#4874 ActualBudget: fix update check (file instead of folder check)
  ct/actualbudget.sh
Labels: update script, bugfix
