Repository community-scripts/ProxmoxVE, pull requests merged in 2025-08, with the labels that each got.

#6434 Refactor: Owncast
  ct/owncast.sh
  frontend/public/json/owncast.json
  install/owncast-install.sh
Labels: update script, json

#6425 Refactor: Overseerr
  ct/overseerr.sh
  install/overseerr-install.sh
Labels: update script, refactor

#6421 Refactor: oauth2-proxy
  ct/oauth2-proxy.sh
  install/oauth2-proxy-install.sh
Labels: update script, refactor

#6419 Refactor: NodeBB
  ct/nodebb.sh
  install/nodebb-install.sh
Labels: update script, refactor

#6403 Refactor: Manage My Damn Life
  ct/managemydamnlife.sh
  install/managemydamnlife-install.sh
Labels: update script, refactor

#6458 Re-Add: Suwayomi-Server
  ct/suwayomiserver.sh
  frontend/public/json/suwayomi-server.json
  install/suwayomiserver-install.sh
Labels: update script, feature

#6443 Immich: Fix immich-admin script; other fixes | pin to v.137.3
  ct/immich.sh
  install/immich-install.sh
Labels: update script, bugfix, json, core

#6459 Fumadocs: add git as dependency
  ct/fumadocs.sh
  install/fumadocs-install.sh
Labels: update script, bugfix

#6517 Fix: Komga uses .komga as storage / so it fails after install
  ct/komga.sh
  install/komga-install.sh
Labels: update script, bugfix

#6525 Refactor: OpenProject
  install/openproject-install.sh
Labels: update script, refactor

#6550 MySpeed: fix update and copy old tests back
  ct/myspeed.sh
Labels: update script, bugfix

#6556 Refactor: PocketID
  ct/pocketid.sh
  install/pocketid-install.sh
Labels: update script, refactor

#6512 turnkey: add hostname & Fix TUN access
  turnkey/turnkey.sh
Labels: update script, feature

#6575 NIC offloading: e1000 support
  tools/pve/nic-offloading-fix.sh
Labels: update script, feature, pve-tool

#6577 Refactor: Prometheus Alertmanager
  ct/prometheus-alertmanager.sh
  install/prometheus-alertmanager-install.sh
Labels: update script, refactor

#6599 PVE9: Remove Beta Whiptail / add correct version check
  misc/build.func
  vm/archlinux-vm.sh
  vm/debian-vm.sh
  vm/docker-vm.sh
  vm/haos-vm.sh
  vm/mikrotik-routeros.sh
  vm/nextcloud-vm.sh
  vm/openwrt.sh
  vm/opnsense-vm.sh
  vm/owncloud-vm.sh
  vm/pimox-haos-vm.sh
  vm/ubuntu2204-vm.sh
  vm/ubuntu2404-vm.sh
  vm/ubuntu2504-vm.sh
  vm/umbrel-os-vm.sh
Labels: update script, feature, core, vm

#6608 [core] better y/N handling for ressource check
  misc/build.func
Labels: update script, bugfix, core

#6632 VictoriaMetrics: Fix release fetching
  ct/victoriametrics.sh
  install/victoriametrics-install.sh
Labels: update script, bugfix

#6628 Feature: Clean-LXC now supports Alpine based containers
  tools/pve/clean-lxcs.sh
  tools/pve/clean.sh
Labels: update script, delete script, feature, pve-tool

#6629 Commafeed: Fix Backup Handling while Update
  ct/commafeed.sh
Labels: update script, bugfix

#6589 Refactor: Paymenter
  ct/paymenter.sh
  install/paymenter-install.sh
Labels: update script, refactor

#6635 Refactor: Tandoor v2
  ct/tandoor.sh
  frontend/public/json/tandoor.json
  install/tandoor-install.sh
Labels: update script, refactor

#6648 Karakeep: workaround/fix for #6593
  ct/karakeep.sh
  install/karakeep-install.sh
Labels: update script, bugfix

#6579 Refactor: Alpine IT-Tools
  ct/alpine-it-tools.sh
  frontend/public/json/alpine-it-tools.json
  install/alpine-it-tools-install.sh
Labels: update script, json

#6669 Immich: unpin libvips revision
  ct/immich.sh
  install/immich-install.sh
Labels: update script, bugfix

#6670 Refactor: ArchiveBox
  ct/archivebox.sh
  ct/bazarr.sh
  frontend/public/json/bazarr.json
  install/archivebox-install.sh
  install/bazarr-install.sh
Labels: update script, json

#6671 Remove: HomeAssistant-Core [deprecated]
  ct/homeassistant-core.sh
  frontend/public/json/homeassistant-core.json
  install/homeassistant-core-install.sh
Labels: breaking change, delete script

#6677 HomeBox: Fix checking for existing install
  ct/homebox.sh
Labels: update script, bugfix

#6680 Unifi: Update libssl dependency
  install/unifi-install.sh
Labels: update script, bugfix

#6673 Refactor: Kometa
  ct/kometa.sh
  install/kometa-install.sh
Labels: update script, refactor

#6662 Refactor: Tianji
  ct/tianji.sh
  install/tianji-install.sh
Labels: update script, refactor

#6653 Improve backup of adventurelog folder
  ct/adventurelog.sh
Labels: update script, bugfix

#6716 Paperless-AI: increase HDD Space to 20G
  ct/paperless-ai.sh
  frontend/public/json/paperless-ai.json
Labels: update script, json

#6729 Karakeep: chromium fix
  install/karakeep-install.sh
Labels: update script, bugfix

#6740 Pulse: fix binary path
  ct/pulse.sh
  install/pulse-install.sh
Labels: update script, bugfix

#6743 Pulse: update config path in JSON
  frontend/public/json/pulse.json
Labels: json

#6744 Reactive Resume: use new release parsing; other fixes
  ct/reactive-resume.sh
  frontend/public/json/reactive-resume.json
  install/reactive-resume-install.sh
Labels: update script, json

#6770 Pulse: binary path changed AGAIN; other fixes
  ct/pulse.sh
  install/pulse-install.sh
Labels: update script, bugfix

#6795 myspeed: fix update process if no data exist
  ct/myspeed.sh
Labels: update script, bugfix

#6804 AgentDVR: Added update function
  ct/agentdvr.sh
  frontend/public/json/agentdvr.json
  install/agentdvr-install.sh
Labels: update script, feature, json

#6803 Docker LXC: Add Portainer info
  ct/docker.sh
Labels: update script, feature

#6820 Refactor: Zwave-JS-UI
  ct/zwave-js-ui.sh
  install/zwave-js-ui-install.sh
Labels: update script, refactor

#6831 Bugfix Searxng Redis replaced with Valkey in installscript
  install/searxng-install.sh
Labels: update script

#6848 Immich: quickfix #6836
  ct/immich.sh
  install/immich-install.sh
Labels: update script, bugfix

#6824 Jenkins change category
  frontend/public/json/jenkins.json
Labels: json

#6829 Refactor: Zipline
  ct/zipline.sh
  frontend/public/json/zipline.json
  install/zipline-install.sh
Labels: update script, json, refactor

#6832 Refactor: yt-dlp-webui
  ct/yt-dlp-webui.sh
  install/yt-dlp-webui-install.sh
Labels: update script, refactor

#6846 ProxmoxVE svg logo
  misc/images/logo-proxmoxve-name.svg
  misc/images/logo-proxmoxve.svg
Labels: maintenance, new script

#6839 Refactor: WireGuard
  ct/wireguard.sh
  frontend/public/json/wireguard.json
  install/wireguard-install.sh
Labels: update script, json, refactor

#6826 Refactor: Zitadel
  ct/zitadel.sh
  install/zitadel-install.sh
Labels: update script, refactor

#6859 Pulse: v4.3.2+
  ct/pulse.sh
  frontend/public/json/pulse.json
  install/pulse-install.sh
Labels: update script, bugfix, json

#6813 Bump Immich to v1.138.0
  ct/immich.sh
  install/immich-install.sh
Labels: update script, feature

#6867 Zitadel: Revert change of starting zitadel service
  install/zitadel-install.sh
Labels: invalid, update script, bugfix

#6869 Refactor: Wavelog
  ct/wavelog.sh
  frontend/public/json/wavelog.json
  install/wavelog-install.sh
Labels: update script, json

#6872 Refactor: Watcharr
  ct/watcharr.sh
  install/watcharr-install.sh
Labels: update script, refactor

#6886 WatchYourLan: Fix update function
  ct/watchyourlan.sh
Labels: invalid, update script, bugfix

#6892 Tandoor Images Fix
  install/tandoor-install.sh
Labels: update script, bugfix

#6898 Wireguard: Fix WGDashboard not updating
  ct/wireguard.sh
Labels: update script, bugfix

#6900 Refactor: Wallos
  ct/wallos.sh
  install/wallos-install.sh
Labels: update script, refactor

#6902 Refactor: Uptime Kuma
  ct/uptimekuma.sh
  frontend/public/json/uptimekuma.json
  install/uptimekuma-install.sh
Labels: update script, json, refactor

#6953 Update hev-socks5-server-install.sh
  install/hev-socks5-server-install.sh
Labels: update script, bugfix

#6961 OpenObserve: Fix release fetching
  ct/openobserve.sh
  frontend/public/json/openobserve.json
Labels: update script, json

#6973 Wallos: Remove unused variable
  install/wallos-install.sh
Labels: invalid, update script, bugfix

#6968 Refactor: Technitium DNS
  ct/technitiumdns.sh
  frontend/public/json/technitiumdns.json
  install/technitiumdns-install.sh
Labels: update script, json, refactor

#6984 Immich: Bump version to 1.138.1
  ct/immich.sh
  install/immich-install.sh
Labels: update script, feature

#6976 Refactor: Glances (+ Feature Bump)
  frontend/public/json/glances.json
  tools/addon/glances.sh
Labels: update script, json, addon

#6990 [web]: update logos from reactive-resume & slskd
  frontend/public/json/reactive-resume.json
  frontend/public/json/slskd.json
Labels: website, json

#7013 PBS: ifupdown2 reload
  install/proxmox-backup-server-install.sh
Labels: update script, bugfix

#7027 Komga: Fix update
  ct/komga.sh
Labels: update script, bugfix

#7031 Post-Install, change pve-test for trixie
  tools/pve/post-pve-install.sh
Labels: update script, pve-tool

#7035 Immich: fix small issue with immich-admin "start" script
  ct/immich.sh
Labels: update script, bugfix

#7044 [core]: improve binary globbing for gh releases
  misc/tools.func
Labels: update script, bugfix, core

#7049 duplicati: fix release pattern
  ct/duplicati.sh
  install/duplicati-install.sh
Labels: update script, bugfix

#7054 Immich: hotfix - revert 7035
  ct/immich.sh
Labels: update script, bugfix

#7066 tianji: add uv deps
  install/tianji-install.sh
Labels: update script, bugfix

#7098 paperless: nltk fix
  install/paperless-ngx-install.sh
Labels: update script, bugfix

#7082 Refactor: Silverbullet
  ct/silverbullet.sh
  install/silverbullet-install.sh
Labels: update script, refactor

#7086 Refactor: RDTClient
  ct/rdtclient.sh
  install/rdtclient-install.sh
Labels: update script, refactor

#7093 Refactor: Prometheus
  ct/prometheus.sh
  frontend/public/json/prometheus.json
  install/prometheus-install.sh
Labels: update script, json

#7140 Kasm: Fix install log parsing
  frontend/public/json/kasm.json
  install/kasm-install.sh
Labels: update script, json

#7171 SnipeIT: Update nginx config to v8.3
  ct/snipeit.sh
  install/snipeit-install.sh
Labels: update script, bugfix

#7172 [core]: uv uses now "update-shell" command
  misc/tools.func
Labels: update script, core

#7191 Add Alpine-RustDesk Server script
  ct/alpine-rustdeskserver.sh
  frontend/public/json/rustdeskserver.json
  install/alpine-rustdeskserver-install.sh
Labels: new script

#7174 FileBrowser Quantum: safer update (tmp download + atomic replace + arch autodetect)
  tools/addon/filebrowser-quantum.sh
Labels: update script, addon

#7198 Komodo: Fix update procedure and missing env var
  ct/komodo.sh
Labels: update script, bugfix

#7199 2FAuth: Fix website and docs URLs
  frontend/public/json/2fauth.json
Labels: website, json

#7138 Immich: bump to v1.139.4
  ct/immich.sh
  install/immich-install.sh
Labels: update script, bugfix

#7212 Refactor: Post-PMG-Script
  tools/pve/post-pmg-install.sh
Labels: update script, pve-tool

#7213 Refactor: Post-PBS-Script
  tools/pve/post-pbs-install.sh
Labels: update script, feature, pve-tool

#7232 Homebox: Fix Update Script
  ct/homebox.sh
Labels: update script, bugfix

#7244 add support for multiple ip addresses in monitor-all.sh
  tools/pve/monitor-all.sh
Labels: update script, pve-tool

#7254 [core]: feature - check_for_gh_release as update-handler
  misc/tools.func
Labels: update script, feature, core

#7256 Keycloak: Update website
  frontend/public/json/keycloak.json
Labels: website, json

#7260 Hoarder: Remove script fragments remains
  ct/headers/hoarder
  ct/hoarder.sh
Labels: delete script

#7266 MMDL: add build-essential as dep
  install/managemydamnlife-install.sh
Labels: update script, bugfix

#7277 Fix typo where install mode was changed instead of pinned version
  install/flaresolverr-install.sh
Labels: update script, bugfix

#7279 [core]: feature - check_for_gh_release - version pinning
  misc/tools.func
Labels: update script, feature, core

#7299 fix: remove file creation at release fetching and version checking logic
  misc/tools.func
Labels: update script, bugfix, core

#7303 Fix: Alpine redlib slug
  frontend/public/json/redlib.json
Labels: bugfix, json

#7320 n8n: Increase disk size
  ct/n8n.sh
  frontend/public/json/n8n.json
Labels: update script, bugfix, json
