Repository community-scripts/ProxmoxVE, pull requests merged in 2025-09, with the labels that each got.

#7329 UmbrelOS: Refactor / use q35 / better import
  vm/umbrel-os-vm.sh
Labels: update script, feature, vm

#7336 Refactor + Feature Bump: HomeAssistant OS
  vm/haos-vm.sh
Labels: update script, vm

#7339 pbs: increase note on website for ipv6
  frontend/public/json/proxmox-backup-server.json
Labels: website, json

#7349 Immich: bump version to 1.140.1
  ct/immich.sh
  frontend/public/json/immich.json
  install/immich-install.sh
Labels: update script, feature, json

#7358 Snipe-IT: Fix Nginx configuration
  ct/snipeit.sh
  install/snipeit-install.sh
Labels: update script, bugfix

#7378 Wizarr: fix uv lock issue; use correct output suppression
  ct/wizarr.sh
  install/wizarr-install.sh
Labels: update script, bugfix

#7384 Element-Synapse: Increase HDD size
  ct/elementsynapse.sh
  frontend/public/json/elementsynapse.json
Labels: update script, bugfix, json

#7398 fix: Syntax error in Immich scripts
  ct/immich.sh
  install/immich-install.sh
Labels: update script, bugfix

#7405 refactor: Enhance ScriptAccordion and Sidebar components to support selectedCategory state
  frontend/next.config.mjs
  frontend/src/app/category-view/page.tsx
  frontend/src/app/scripts/_components/script-accordion.tsx
  frontend/src/app/scripts/_components/sidebar.tsx
  frontend/src/app/scripts/page.tsx
Labels: website, refactor

#7408 MediaManager Configuration Path
  frontend/public/json/mediamanager.json
Labels: website, json

#7423 use debian source for direct installation of MQTT
  install/mqtt-install.sh
Labels: update script

#7164 feat: added mobile ui subscription nag removal
  tools/pve/post-pve-install.sh
Labels: update script, feature, pve-tool

#7469 Update searxng-install.sh
  install/searxng-install.sh
Labels: update script, bugfix

#7464 feat: enhance github stars button to be better looking and more compact
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/animate-ui/components/buttons/button.tsx
  frontend/src/components/animate-ui/components/buttons/github-stars.tsx
  frontend/src/components/animate-ui/primitives/animate/github-stars.tsx
  frontend/src/components/animate-ui/primitives/animate/slot.tsx
  frontend/src/components/animate-ui/primitives/buttons/button.tsx
  frontend/src/components/animate-ui/primitives/effects/particles.tsx
  frontend/src/components/animate-ui/primitives/texts/sliding-number.tsx
  frontend/src/components/navbar.tsx
  frontend/src/hooks/use-is-in-view.tsx
  frontend/src/lib/get-strict-context.tsx
Labels: website, feature

#7505 PLANKA: Fix backup and restore commands
  ct/planka.sh
Labels: update script, bugfix

#7511 swizzin: Change category from nvr to media
  frontend/public/json/swizzin.json
Labels: website, json

#7533 Booklore: Add Bookdrop location to .env
  install/booklore-install.sh
Labels: update script, feature

#7534 set updateable to true for several lxc JSON-configs
  frontend/public/json/add-netbird-lxc.json
  frontend/public/json/add-tailscale-lxc.json
  frontend/public/json/apt-cacher-ng.json
  frontend/public/json/beszel.json
  frontend/public/json/cloudflare-ddns.json
  frontend/public/json/cloudflared.json
  frontend/public/json/dashy.json
  frontend/public/json/deconz.json
  frontend/public/json/deluge.json
  frontend/public/json/fhem.json
  frontend/public/json/filebrowser-quantum.json
  frontend/public/json/filebrowser.json
  frontend/public/json/homebridge.json
  frontend/public/json/hyperhdr.json
  frontend/public/json/influxdb.json
  frontend/public/json/jeedom.json
  frontend/public/json/jenkins.json
  frontend/public/json/lazylibrarian.json
  frontend/public/json/lldap.json
  frontend/public/json/mariadb.json
  frontend/public/json/mattermost.json
  frontend/public/json/mongodb.json
  frontend/public/json/mqtt.json
  frontend/public/json/ntfy.json
  frontend/public/json/omv.json
  frontend/public/json/openhab.json
  frontend/public/json/pialert.json
  frontend/public/json/radicale.json
  frontend/public/json/smokeping.json
  frontend/public/json/syncthing.json
  frontend/public/json/tautulli.json
  frontend/public/json/unifi.json
Labels: website, json

#7540 fix: pmg - split no-nag script into separate config files
  tools/pve/post-pmg-install.sh
Labels: update script, pve-tool

#7537 Refactor: Blocky
  ct/blocky.sh
  frontend/public/json/blocky.json
  install/blocky-install.sh
Labels: update script, json, refactor

#7552 Wizarr: Fix DB migrations
  ct/wizarr.sh
  install/wizarr-install.sh
Labels: update script, bugfix

#7558 Palmr: fix #7556
  ct/palmr.sh
  install/palmr-install.sh
Labels: update script, bugfix

#7594 Immich: bump to v1.142.0
  ct/immich.sh
  install/immich-install.sh
Labels: update script, core, refactor

#7620 ollama: fix: ccurl continue on interrupts
  ct/ollama.sh
  install/ollama-install.sh
Labels: update script, bugfix, refactor

#7619 pdm: refactor for beta version
  ct/proxmox-datacenter-manager.sh
  install/proxmox-datacenter-manager-install.sh
Labels: update script, refactor

#7621 fix: tagline grammar
  frontend/src/app/page.tsx
Labels: website

#7625 Palmr: hotfix #7622
  ct/palmr.sh
Labels: update script, bugfix

#7660 Cloudflare-DDNS: Fix the IP6_PROVIDER variable
  install/cloudflare-ddns-install.sh
Labels: update script, bugfix

#7667 hortusfox: fix update check
  ct/hortusfox.sh
Labels: update script, bugfix

#7669 Improve OpenWrt VM boot and readiness check
  vm/openwrt-vm.sh
Labels: update script, vm

#7675 Bump Immich to v1.142.1
  ct/immich.sh
  install/immich-install.sh
Labels: update script, feature

#7690 Improve: SECURITY.md for clarity and detail + Adding PVE9 as supported
  SECURITY.md
Labels: maintenance, github

#7705 Gatus: check for GO path before update
  ct/gatus.sh
Labels: update script, bugfix

#7711 Alpine-Caddy
  ct/alpine-caddy.sh
  frontend/public/json/caddy.json
  install/alpine-caddy-install.sh
Labels: new script, json

#7719 Cloudflared: Bump to Debian 13
  ct/cloudflared.sh
  frontend/public/json/cloudflared.json
  install/cloudflared-install.sh
Labels: update script, feature, json

#7725 Delay chmod after updating beszel
  ct/beszel.sh
Labels: update script, bugfix, refactor

#7728 Immich: Debian Trixie
  ct/immich.sh
  frontend/public/json/immich.json
  install/immich-install.sh
Labels: update script, json, refactor

#7742 SigNoz: Fix wrong URL for Zookeeper
  install/signoz-install.sh
Labels: update script, bugfix

#7757 Add Debian 13 in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: maintenance, github

#7759 Wazuh: Increase HDD size
  ct/wazuh.sh
  frontend/public/json/wazuh.json
Labels: update script, bugfix, json

#7765 checkmk.sh Update: Revert old Pr
  ct/checkmk.sh
Labels: update script

#7773 Harmonize and shorten JSON Names for PVE/PBS/PMG
  frontend/public/json/add-iptag.json
  frontend/public/json/clean-lxcs.json
  frontend/public/json/clean-orphaned-lvm.json
  frontend/public/json/cron-update-lxcs.json
  frontend/public/json/fstrim.json
  frontend/public/json/host-backup.json
  frontend/public/json/kernel-clean.json
  frontend/public/json/kernel-pin.json
  frontend/public/json/microcode.json
  frontend/public/json/monitor-all.json
  frontend/public/json/netdata.json
  frontend/public/json/pbs-microcode.json
  frontend/public/json/post-pbs-install.json
  frontend/public/json/post-pmg-install.json
  frontend/public/json/post-pve-install.json
  frontend/public/json/proxmox-backup-server.json
  frontend/public/json/proxmox-datacenter-manager.json
  frontend/public/json/proxmox-mail-gateway.json
  frontend/public/json/scaling-governor.json
  frontend/public/json/update-lxcs.json
  frontend/public/json/update-repo.json
Labels: json

#7775 caddy: modify disk size and implement xCaddy update
  ct/caddy.sh
  frontend/public/json/caddy.json
Labels: update script, feature, json

#7785 Implement clean install option in tools.func (fetch_and_deploy_gh_release)
  misc/tools.func
Labels: update script, feature, core

#7782 tracktor: add: cleanup before upgrade
  ct/tracktor.sh
Labels: update script, bugfix

#7792 Paymenter: Installation and update fixes
  ct/paymenter.sh
  install/paymenter-install.sh
Labels: update script, bugfix

#7872 Update name in lxc-delete.json to 'PVE LXC Deletion'
  frontend/public/json/lxc-delete.json
Labels: website, json

#7877 Monica: Fix dependencies
  ct/monica.sh
  install/monica-install.sh
Labels: update script, bugfix

#7919 OpenWebUI: Update NODE_OPTIONS to increase memory limit
  ct/openwebui.sh
  install/openwebui-install.sh
Labels: update script, bugfix

#7931 Odoo: Fix missing dependencies
  ct/odoo.sh
  install/odoo-install.sh
Labels: update script, bugfix

#7941 Oddo: Fix typo in update procedure
  ct/odoo.sh
Labels: update script, bugfix

#7936 MeTube: Various fixes
  ct/metube.sh
  install/metube-install.sh
Labels: update script, bugfix, core, refactor

#7987 Improve mobile ui: added a hamburger navigation to the mobile view.
  frontend/src/app/layout.tsx
  frontend/src/app/scripts/_components/script-accordion.tsx
  frontend/src/app/scripts/_components/sidebar.tsx
  frontend/src/components/navbar.tsx
  frontend/src/components/navigation/mobile-sidebar.tsx
  frontend/src/components/ui/command.tsx
Labels: website, feature

#7991 fix sidebar loading issues and navbar on mobile
  frontend/src/components/navbar.tsx
  frontend/src/components/navigation/mobile-sidebar.tsx
  frontend/src/lib/data.ts
Labels: website, bugfix

#8010 Bump Guacamole to Debian 13
  ct/apache-guacamole.sh
  frontend/public/json/apache-guacamole.json
  install/apache-guacamole-install.sh
Labels: update script, feature, json
